const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const list=v=>Array.isArray(v)?v.filter(x=>x&&x.enabled!==false):[];
const money=(n)=>'₹'+new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Math.max(0,num(n)));
export function render(d={},selected=[]){
  const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},os=d.pickup||{},ok=x=>selected.includes(x);
  const services=list(d.services),packages=list(d.packages),vehicles=list(d.vehicleTypes),ba=list(d.beforeAfter),gallery=list(d.gallery),specials=list(d.specials),team=list(d.team),trust=list(d.trust),reviews=list(d.reviews),faq=list(d.faq),hours=list(d.hours);
  const cats=[...new Set(gallery.map(x=>x.category).filter(Boolean))];
  let html='<div class="site-preview automotive-01">';
  html+='<header class="au-nav"><a class="au-brand" href="#home"><span class="au-mark">DC</span><span><strong>'+esc(b.businessName||"Your Auto Studio")+'</strong><small>'+esc(b.tagline||"SERVICE · DETAILING · CARE")+'</small></span></a><nav>';
  if(ok('home'))html+='<a href="#home">Home</a>';if(ok('services'))html+='<a href="#services">Services</a>';if(ok('packages'))html+='<a href="#packages">Packages</a>';if(ok('vehicle'))html+='<a href="#vehicle">Vehicle</a>';if(ok('booking'))html+='<a href="#booking">Book</a>';if(ok('beforeAfter'))html+='<a href="#beforeAfter">Results</a>';if(ok('location'))html+='<a href="#location">Location</a>';
  html+='</nav><div class="au-nav-actions">'+(ok('whatsapp')&&c.whatsapp?'<a class="au-mini au-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+'<a class="template-admin-link" href="admin.html?template=automotive-01">Admin</a></div></header>';

  if(ok('home')&&s.showHome!==false)html+='<section id="home" class="au-hero"><div class="au-hero-copy"><span class="au-kicker">AUTOMOTIVE SERVICE · DETAILING · DIAGNOSTICS</span><h1>'+esc(h.title||"Keep your car looking and driving its best.")+'</h1><p>'+esc(h.text||"Routine service, diagnostics and detailing from one workshop.")+'</p><div class="au-actions">'+(ok('booking')?'<a class="au-btn solid" href="#booking">Book a Service <span>↗</span></a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="au-btn light" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp Workshop</a>':'')+'</div><div class="au-stats"><div><strong>'+esc(b.carsServed||0)+'+</strong><span>cars served</span></div><div><strong>'+esc(b.years||0)+' yrs</strong><span>workshop experience</span></div><div><strong>Clear</strong><span>estimates & updates</span></div></div></div><div class="au-hero-media">'+(d.heroVideo?'<video autoplay muted loop playsinline poster="'+esc(d.hero||"")+'"><source src="'+esc(d.heroVideo)+'" type="video/mp4"></video>':'<img src="'+esc(d.hero||"")+'" alt="'+esc(b.businessName||"Automotive workshop")+'">')+'<div class="au-hero-chip"><span>WORKSHOP NOTE</span><strong>Service first.<br>Guesswork never.</strong></div></div></section>';

  if(ok('services')&&s.showServices!==false)html+='<section id="services" class="au-section"><div class="au-head split"><div><span class="au-kicker">SERVICES & PRICING</span><h2>Choose the service your vehicle needs.</h2></div><p>Starting prices are indicative. Final pricing depends on vehicle type, parts, labour and inspection findings.</p></div><div class="au-service-grid">'+services.map((x,i)=>'<article><span class="au-service-icon">'+esc(x.icon||"🛠️")+'</span><div><small>'+esc(x.category||"Service")+'</small><h3>'+esc(x.name||"Service")+'</h3><p>'+esc(x.description||"")+'</p></div><strong>'+money(x.basePrice||0)+'+</strong><button type="button" class="au-link-btn" data-service="'+esc(x.name||"")+'">Select ↗</button></article>').join('')+'</div></section>';

  if(ok('packages')&&s.showPackages!==false)html+='<section id="packages" class="au-section au-packages"><div class="au-head split"><div><span class="au-kicker">SERVICE PACKAGES</span><h2>Package the visit around the job.</h2></div><p>Package prices are sample starting points and should be confirmed before work begins.</p></div><div class="au-package-grid">'+packages.map((x,i)=>'<article class="'+(x.tier==="Luxury"?'featured':'')+'"><div class="au-package-top"><span>'+esc(x.tier||"Package")+'</span><small>0'+(i+1)+'</small></div><h3>'+esc(x.name||"Package")+'</h3><strong>'+esc(x.price||"Custom quote")+'</strong><em>'+esc(x.vehicle||"All vehicles")+'</em><p>'+esc(x.summary||"")+'</p><ul>'+((Array.isArray(x.includes)?x.includes:String(x.includes||"").split(",").map(v=>v.trim()).filter(Boolean))).map(v=>'<li>✓ '+esc(v)+'</li>').join('')+'</ul><a class="au-btn '+(x.tier==="Luxury"?'solid':'outline')+'" href="#booking" data-package="'+esc(x.name||"")+'">Book this package <span>↗</span></a></article>').join('')+'</div></section>';

  if(ok('vehicle')&&s.showVehicle!==false)html+='<section id="vehicle" class="au-section au-vehicle"><div class="au-head"><span class="au-kicker">VEHICLE TYPE</span><h2>Start with what you drive.</h2></div><div class="au-vehicle-grid">'+vehicles.map((x,i)=>'<button type="button" class="au-vehicle-card '+(i===0?'active':'')+'" data-vehicle="'+esc(x.name)+'" data-multiplier="'+num(x.multiplier)+'"><span>'+esc(x.icon||"🚗")+'</span><strong>'+esc(x.name)+'</strong><small>Pricing guide × '+num(x.multiplier).toFixed(2)+'</small></button>').join('')+'</div><div class="au-vehicle-note"><span>Selected vehicle</span><strong id="auSelectedVehicle">'+esc(vehicles[0]?.name||"Choose vehicle")+'</strong></div></section>';

  if(ok('booking')&&s.showBooking!==false)html+='<section id="booking" class="au-section au-booking"><div class="au-booking-copy"><span class="au-kicker">SERVICE BOOKING</span><h2>'+esc(d.booking?.heading||"Book a service visit.")+'</h2><p>'+esc(d.booking?.text||"Tell us what you drive and when you want to visit.")+'</p><div class="au-booking-links">'+(ok('call')&&c.phone?'<a href="tel:'+safe(c.phone)+'"><span>Call</span>'+esc(c.phone)+'</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'"><span>WhatsApp</span>Chat with workshop</a>':'')+'</div></div><form id="auBookingForm" class="au-form"><div class="au-form-grid"><label>Name<input name="name" required placeholder="Your name"></label><label>Phone<input name="phone" required type="tel" placeholder="+91"></label><label>Email<input name="email" type="email" placeholder="you@example.com"></label><label>Vehicle Type<select name="vehicleType" id="auVehicleSelect">'+vehicles.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label>Service<select name="service" id="auServiceSelect"><option value="">Choose a service</option>'+services.map(x=>'<option value="'+esc(x.name)+'" data-price="'+num(x.basePrice)+'">'+esc(x.name)+' — '+money(x.basePrice||0)+'+</option>').join('')+'</select></label><label>Package<select name="package" id="auPackageSelect"><option value="">No package</option>'+packages.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label>Service Date<input name="serviceDate" type="date"></label><label>Time Slot<select name="timeSlot"><option>8:30 AM – 10:00 AM</option><option>10:00 AM – 12:00 PM</option><option>12:00 PM – 2:00 PM</option><option>2:00 PM – 4:00 PM</option><option>4:00 PM – 6:00 PM</option><option>6:00 PM – 7:30 PM</option></select></label><label class="full">Pickup / Drop Location<input name="location" placeholder="Area / address"></label><label>Pickup & Drop<select name="pickupDrop"><option>No</option><option>Pickup & Drop Required</option></select></label><label>Estimated Budget<input name="budget" placeholder="Optional"></label></div><label>Message<textarea name="message" placeholder="Car model, registration year, issue or special request"></textarea></label><div class="au-form-foot"><span id="auBookingNotice"></span><button class="au-btn solid" type="submit">'+esc(d.booking?.buttonText||"Book Service on WhatsApp")+' <span>↗</span></button></div></form></section>';

  if(ok('pickup')&&s.showPickup!==false)html+='<section class="au-section au-pickup"><div class="au-head split"><div><span class="au-kicker">PICKUP & DROP</span><h2>Make the service visit easier.</h2></div><p>'+esc(os.note||"Request pickup and drop where available.")+'</p></div><div class="au-pickup-grid"><article><span>AREA</span><strong>'+esc(os.serviceArea||c.serviceArea||"Selected service areas")+'</strong></article><article><span>CHARGE</span><strong>'+esc(os.feeText||"Confirmed during booking")+'</strong></article><article><span>PROCESS</span><strong>Request → Confirmation → Pickup → Service → Delivery</strong></article></div></section>';

  if(ok('beforeAfter')&&s.showBeforeAfter!==false)html+='<section id="beforeAfter" class="au-section au-results"><div class="au-head split"><div><span class="au-kicker">BEFORE / AFTER</span><h2>Show the work, not just the promise.</h2></div><p>Drag the slider to compare the starting condition with the finished result.</p></div><div class="au-ba-grid">'+ba.map((x,i)=>'<article class="au-ba-card"><div class="au-ba-title"><span>0'+(i+1)+'</span><div><strong>'+esc(x.title||"Transformation")+'</strong><small>'+esc(x.category||"Service")+'</small></div></div><div class="au-ba-stage"><img src="'+esc(x.after||"")+'" alt="After '+esc(x.title||"")+'"><div class="au-ba-before"><img src="'+esc(x.before||"")+'" alt="Before '+esc(x.title||"")+'"></div><div class="au-ba-divider"><span>BEFORE / AFTER</span></div><input class="au-ba-range" type="range" min="0" max="100" value="50" aria-label="Before after comparison"></div><div class="au-ba-labels"><span>Before</span><span>After</span></div><p>'+esc(x.note||"")+'</p></article>').join('')+'</div></section>';

  if(ok('specials')&&s.showSpecials!==false)html+='<section class="au-section au-specials"><div class="au-head"><span class="au-kicker">OFFERS & SPECIALS</span><h2>Useful upgrades for the next visit.</h2></div><div class="au-special-grid">'+specials.map(x=>'<article><span>✦</span><h3>'+esc(x.title)+'</h3><p>'+esc(x.text||"")+'</p></article>').join('')+'</div></section>';

  if(ok('gallery')&&s.showGallery!==false)html+='<section class="au-section"><div class="au-head split"><div><span class="au-kicker">WORKSHOP GALLERY</span><h2>See the place behind the service.</h2></div><p>Filter workshop, detailing, service and premium work photos.</p></div><div class="au-filter-row"><button class="au-filter active" data-gallery-cat="all">All</button>'+cats.map(x=>'<button class="au-filter" data-gallery-cat="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><div class="au-gallery">'+gallery.map(x=>'<figure data-gallery-item="'+esc(x.category||"Other")+'"><img src="'+esc(x.image||"")+'" alt="'+esc(x.title||"Workshop")+'"><figcaption><strong>'+esc(x.title||"Workshop")+'</strong><span>'+esc(x.category||"")+'</span></figcaption></figure>').join('')+'</div></section>';

  if(ok('team')&&s.showTeam!==false)html+='<section class="au-section au-team"><div class="au-head"><span class="au-kicker">TECHNICIANS & EXPERTS</span><h2>Meet the people working on the vehicle.</h2></div><div class="au-team-grid">'+team.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Technician")+'"><div><span>'+esc(x.role||"")+'</span><h3>'+esc(x.name||"Technician")+'</h3><p>'+esc(x.specialization||"")+'</p><small>'+esc(x.credentials||"")+'</small></div></article>').join('')+'</div></section>';

  if(ok('trust')&&s.showTrust!==false)html+='<section class="au-section au-trust"><div class="au-head split"><div><span class="au-kicker">BRANDS, WARRANTY & TRUST</span><h2>Make workshop standards easy to verify.</h2></div><p>Only publish actual parts brands, warranty terms, technician qualifications and workshop claims that apply to your business.</p></div><div class="au-trust-grid">'+trust.map(x=>'<article><span>✓</span><h3>'+esc(x.title||"Trust point")+'</h3><p>'+esc(x.text||"")+'</p></article>').join('')+'</div></section>';

  if(ok('reviews')&&s.showReviews!==false)html+='<section class="au-section au-reviews"><div class="au-head"><span class="au-kicker">CUSTOMER REVIEWS</span><h2>What owners say about the service.</h2></div><div class="au-review-grid">'+reviews.map(x=>'<article>'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name||"Customer")+'">':'')+'<div class="au-stars">'+('★'.repeat(Math.max(1,Math.min(5,num(x.rating)||5))))+'</div><p>“'+esc(x.text||"")+'”</p><strong>'+esc(x.name||"Customer")+'</strong><small>'+esc(x.event||"Service")+'</small></article>').join('')+'</div></section>';

  if(ok('about')&&s.showAbout!==false)html+='<section class="au-section au-about"><div class="au-head split"><div><span class="au-kicker">ABOUT THE WORKSHOP</span><h2>'+esc(b.about||"Tell your workshop story here.")+'</h2></div><p>Share the workshop background, experience, service philosophy and what customers can expect.</p></div><div class="au-about-stats"><div><strong>'+esc(b.years||0)+'+</strong><span>years in service</span></div><div><strong>'+esc(b.carsServed||0)+'+</strong><span>cars served</span></div><div><strong>Direct</strong><span>booking & updates</span></div></div></section>';

  if(ok('faq')&&s.showFAQ!==false)html+='<section class="au-section"><div class="au-head"><span class="au-kicker">FAQ</span><h2>Before you book.</h2></div><div class="au-faq">'+faq.map(x=>'<details><summary>'+esc(x.question||"Question")+'<span>+</span></summary><p>'+esc(x.answer||"")+'</p></details>').join('')+'</div></section>';

  if(ok('location')||ok('hours'))html+='<section id="location" class="au-section au-location"><div><span class="au-kicker">WORKSHOP LOCATION</span><h2>'+esc(b.businessName||"Your Workshop")+'</h2><p>'+esc(c.address||"Add workshop address here.")+'</p><p>'+esc(c.hoursText||"")+'</p><div class="au-actions">'+(ok('call')&&c.phone?'<a class="au-btn solid" href="tel:'+safe(c.phone)+'">Call Workshop</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="au-btn outline" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+'</div></div>'+(c.maps?'<a class="au-map" target="_blank" href="'+esc(c.maps)+'"><span>OPEN MAP</span><strong>Get directions ↗</strong><small>'+esc(c.address||"Workshop location")+'</small></a>':'')+'</section>';

  if(ok('hours'))html+='<section class="au-section au-hours"><div class="au-head"><span class="au-kicker">OPENING HOURS</span><h2>Bring the car during workshop hours.</h2></div><div class="au-hours-list">'+hours.map(x=>'<div><strong>'+esc(x.day||"Day")+'</strong><span>'+esc(x.enabled!==false?(x.open||"")+" — "+(x.close||""):"Closed")+'</span></div>').join('')+'</div></section>';

  if(ok('terms')||ok('privacy'))html+='<section class="au-legal">'+(ok('terms')?'<details open><summary>Service Terms & Warranty</summary><p>'+esc(d.termsText||"")+'</p></details>':'')+(ok('privacy')?'<details><summary>Privacy Policy</summary><p>'+esc(d.privacyPolicy||"")+'</p></details>':'')+'</section>';
  html+='<footer class="au-footer"><div><strong>'+esc(b.businessName||"Your Workshop")+'</strong><span>'+esc(b.tagline||"")+'</span></div><div>'+(ok('call')&&c.phone?'<a href="tel:'+safe(c.phone)+'">Call</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">Email</a>':'')+'</div></footer>';
  if(ok('whatsapp')&&c.whatsapp)html+='<a class="au-float-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp ↗</a>';
  return html+'</div>';
}
export function init(root,d={}){
  let selectedVehicle=root.querySelector('#auVehicleSelect')?.value||'';
  root.querySelectorAll('[data-vehicle]').forEach(b=>b.onclick=()=>{root.querySelectorAll('.au-vehicle-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedVehicle=b.dataset.vehicle||'';const v=root.querySelector('#auVehicleSelect');if(v){v.value=selectedVehicle;v.dispatchEvent(new Event('change'))}const out=root.querySelector('#auSelectedVehicle');if(out)out.textContent=selectedVehicle});
  root.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{const s=root.querySelector('#auServiceSelect');if(s){s.value=b.dataset.service||'';s.dispatchEvent(new Event('change'))}root.querySelector('#booking')?.scrollIntoView({behavior:'smooth'})});
  root.querySelectorAll('[data-package]').forEach(b=>b.onclick=()=>{const p=root.querySelector('#auPackageSelect');if(p){p.value=b.dataset.package||'';p.dispatchEvent(new Event('change'))}root.querySelector('#booking')?.scrollIntoView({behavior:'smooth'})});
  root.querySelectorAll('.au-filter').forEach(b=>b.onclick=()=>{root.querySelectorAll('.au-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const cat=b.dataset.galleryCat;root.querySelectorAll('[data-gallery-item]').forEach(x=>x.hidden=cat!=='all'&&x.dataset.galleryItem!==cat)});
  root.querySelectorAll('.au-ba-card').forEach(card=>{const r=card.querySelector('.au-ba-range'),layer=card.querySelector('.au-ba-before'),divider=card.querySelector('.au-ba-divider');const sync=()=>{const p=num(r?.value||50);if(layer)layer.style.clipPath='inset(0 '+(100-p)+'% 0 0)';if(divider)divider.style.left=p+'%'};r?.addEventListener('input',sync);sync()});
  const form=root.querySelector('#auBookingForm');
  if(form)form.addEventListener('submit',ev=>{
    ev.preventDefault();
    const fd=new FormData(form),lead=Object.fromEntries(fd.entries());
    const service=form.querySelector('#auServiceSelect')?.selectedOptions?.[0],vehicle=form.querySelector('#auVehicleSelect')?.value||'';
    const mult=(d.vehicleTypes||[]).find(x=>x.name===vehicle)?.multiplier||1;
    const base= num(service?.dataset?.price||0)*num(mult);
    lead.total=base?money(base):'To be confirmed';lead.status='New';lead.createdAt=new Date().toISOString();
    try{const state=Store.read(),data=structuredClone(state.data||d||{});data.leads=Array.isArray(data.leads)?data.leads:[];data.leads.unshift(lead);Store.update({data});const n=root.querySelector('#auBookingNotice');if(n)n.textContent='Booking request saved. The workshop will confirm the service, estimate and appointment slot.';form.reset()}catch{const n=root.querySelector('#auBookingNotice');if(n)n.textContent='Could not save the booking in this browser.'}
    const wa=d.contact?.whatsapp;
    if(wa){const msg=['Automotive service booking',lead.name,lead.phone,lead.email,'Vehicle: '+lead.vehicleType,'Service: '+lead.service,'Package: '+lead.package, 'Date: '+lead.serviceDate,'Slot: '+lead.timeSlot,'Location: '+lead.location,'Pickup/Drop: '+lead.pickupDrop,'Estimate: '+lead.total,lead.message].filter(Boolean).join('\n');window.open('https://wa.me/'+safe(wa)+'?text='+encodeURIComponent(msg),'_blank')}
  });
}