const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const list=v=>Array.isArray(v)?v.filter(x=>x&&x.enabled!==false):[];
export function render(d={},selected=[]){
  const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},ok=x=>selected.includes(x);
  const eventTypes=list(d.eventTypes),packages=list(d.packages),services=list(d.services),gallery=list(d.gallery),videos=list(d.videos),venues=list(d.venues),
        availability=list(d.availability),reviews=list(d.reviews),team=list(d.team),faq=list(d.faq),hours=list(d.hours);
  const cats=[...new Set(gallery.map(x=>x.category).filter(Boolean))];
  let html='<div class="site-preview event-wedding-01">';
  html+='<header class="ew-nav"><a class="ew-brand" href="#home"><span class="ew-mark">CE</span><span><strong>'+esc(b.businessName||"Your Events Studio")+'</strong><small>'+esc(b.tagline||"EVENTS · WEDDINGS · CELEBRATIONS")+'</small></span></a><nav>';
  if(ok('home'))html+='<a href="#home">Home</a>';if(ok('eventTypes'))html+='<a href="#eventTypes">Events</a>';if(ok('packages'))html+='<a href="#packages">Packages</a>';
  if(ok('services'))html+='<a href="#services">Services</a>';if(ok('gallery'))html+='<a href="#gallery">Work</a>';if(ok('venues'))html+='<a href="#venues">Venues</a>';
  if(ok('availability'))html+='<a href="#availability">Dates</a>';if(ok('enquiry'))html+='<a href="#enquiry">Enquiry</a>';
  html+='</nav><div class="ew-nav-actions">'+(ok('whatsapp')&&c.whatsapp?'<a class="ew-mini ew-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+'<a class="template-admin-link" href="admin.html?template=event-wedding-01">Admin</a></div></header>';

  if(ok('home')&&s.showHome!==false)html+='<section id="home" class="ew-hero"><div class="ew-hero-copy"><span class="ew-kicker">WEDDINGS · EVENTS · EXPERIENCES</span><h1>'+esc(h.title||"Your celebration, beautifully planned.")+'</h1><p>'+esc(h.text||"We plan the details so you can live the moment.")+'</p><div class="ew-actions">'+(ok('enquiry')?'<a class="ew-btn solid" href="#enquiry">Plan Your Event <span>↗</span></a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="ew-btn light" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp Planner</a>':'')+'</div><div class="ew-hero-stats"><div><strong>'+esc(b.eventsCompleted||0)+'+</strong><span>events completed</span></div><div><strong>'+esc(b.experienceYears||0)+' yrs</strong><span>experience</span></div><div><strong>One team</strong><span>from brief to event day</span></div></div></div><div class="ew-hero-media">'+(d.heroVideo?'<video autoplay muted loop playsinline poster="'+esc(d.hero||'')+'"><source src="'+esc(d.heroVideo)+'" type="video/mp4"></video>':'<img src="'+esc(d.hero||'')+'" alt="'+esc(b.businessName||"Event planner")+'">')+'<div class="ew-hero-chip"><span>CELEBRATION NOTE</span><strong>Beautiful moments.<br>Handled with care.</strong></div></div></section>';

  if(ok('eventTypes')&&s.showEventTypes!==false)html+='<section id="eventTypes" class="ew-section ew-eventtypes"><div class="ew-head split"><div><span class="ew-kicker">EVENT TYPES</span><h2>Different celebrations. One thoughtful planning process.</h2></div><p>Choose the type of event you are planning and use the enquiry form to request a tailored package.</p></div><div class="ew-event-grid">'+eventTypes.map((x,i)=>'<article><span class="ew-event-icon">'+esc(x.icon||"✦")+'</span><small>0'+(i+1)+'</small><h3>'+esc(x.name)+'</h3><p>'+esc(x.description||"")+'</p><a href="#enquiry" data-event-type="'+esc(x.name)+'">Plan this event ↗</a></article>').join('')+'</div></section>';

  if(ok('packages')&&s.showPackages!==false)html+='<section id="packages" class="ew-section"><div class="ew-head split"><div><span class="ew-kicker">PACKAGES & PRICING</span><h2>Clear starting points, tailored to your celebration.</h2></div><p>Displayed pricing is a sample starting point. Final scope, vendor rates and event requirements should be confirmed in the written proposal.</p></div><div class="ew-package-grid">'+packages.map((x,i)=>'<article class="ew-package-card '+(x.tier==="Luxury"?'featured':'')+'"><div class="ew-package-top"><span>'+esc(x.tier||"Package")+'</span><small>0'+(i+1)+'</small></div><h3>'+esc(x.name)+'</h3><strong>'+esc(x.price||"Custom Quote")+'</strong><em>'+esc(x.starting||"Based on scope")+'</em><p>'+esc(x.guestRange||"Custom guest count")+'</p><p class="ew-package-summary">'+esc(x.summary||"")+'</p><ul>'+((Array.isArray(x.includes)?x.includes:String(x.includes||"").split(",").map(y=>y.trim()).filter(Boolean))).map(y=>'<li>✓ '+esc(y)+'</li>').join('')+'</ul><a class="ew-btn '+(x.tier==="Luxury"?'solid':'outline')+'" href="#enquiry" data-package="'+esc(x.name||"")+'">Discuss package <span>↗</span></a></article>').join('')+'</div></section>';

  if(ok('services')&&s.showServices!==false)html+='<section id="services" class="ew-section ew-dark"><div class="ew-head"><span class="ew-kicker">OUR SERVICES</span><h2>Every moving part, coordinated with intention.</h2></div><div class="ew-service-grid">'+services.map((x,i)=>'<article><span class="ew-service-icon">'+esc(x.icon||"✦")+'</span><small>0'+(i+1)+'</small><h3>'+esc(x.name)+'</h3><p>'+esc(x.description||"")+'</p></article>').join('')+'</div></section>';

  if(ok('gallery')&&s.showGallery!==false)html+='<section id="gallery" class="ew-section"><div class="ew-head split"><div><span class="ew-kicker">OUR WORK</span><h2>Past celebrations, styled with a point of view.</h2></div><p>Use categories to showcase weddings, engagements, birthdays, corporate events and other work.</p></div><div class="ew-filter-row"><button class="ew-filter active" data-gallery-cat="all">All</button>'+cats.map(x=>'<button class="ew-filter" data-gallery-cat="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><div class="ew-gallery">'+gallery.map((x,i)=>'<figure data-gallery-item="'+esc(x.category||"Other")+'"><img src="'+esc(x.image||"")+'" alt="'+esc(x.title||"Event")+'"><figcaption><strong>'+esc(x.title||"Event")+'</strong><span>'+esc(x.category||"Celebration")+'</span></figcaption></figure>').join('')+'</div></section>';

  if(ok('videos')&&videos.length)html+='<section class="ew-section ew-video"><div class="ew-head split"><div><span class="ew-kicker">EVENT FILMS</span><h2>Let future clients see how you work.</h2></div><p>Replace sample URLs with your own wedding reels, setup walkthroughs and behind-the-scenes videos.</p></div><div class="ew-video-grid">'+videos.map((x,i)=>'<article><a target="_blank" href="'+esc(x.url||"#")+'"><div class="ew-video-thumb">'+(x.thumbnail?'<img src="'+esc(x.thumbnail)+'" alt="'+esc(x.title||"Video")+'">':'')+'<span>▶</span></div><strong>'+esc(x.title||"Event video")+'</strong><p>'+esc(x.description||"")+'</p></a></article>').join('')+'</div></section>';

  if(ok('venues')&&venues.length)html+='<section id="venues" class="ew-section ew-venues"><div class="ew-head split"><div><span class="ew-kicker">VENUE SHOWCASE</span><h2>Help clients imagine where the celebration could happen.</h2></div><p>Show capacity, indoor/outdoor format, parking and location notes for preferred venues.</p></div><div class="ew-venue-grid">'+venues.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Venue")+'"><div><div class="ew-venue-meta"><span>'+esc(x.type||"Venue")+'</span><span>'+esc(x.capacity||"")+'</span></div><h3>'+esc(x.name||"Venue")+'</h3><p>'+esc(x.area||"")+'</p><div class="ew-venue-details"><span>Parking: '+esc(x.parking||"—")+'</span><span>'+esc(x.indoorOutdoor||"")+'</span></div>'+(x.maps?'<a class="ew-link" target="_blank" href="'+esc(x.maps)+'">View venue location ↗</a>':'')+'</div></article>').join('')+'</div></section>';

  if(ok('availability')&&s.showAvailability!==false)html+='<section id="availability" class="ew-section ew-availability"><div class="ew-head split"><div><span class="ew-kicker">DATE AVAILABILITY</span><h2>Check the planning calendar before you enquire.</h2></div><p>Availability is a planning guide. Dates still require confirmation from the event team.</p></div><div class="ew-date-grid">'+availability.map(x=>'<button type="button" class="ew-date-card ew-'+esc(String(x.status||"Enquiry").toLowerCase())+'" data-availability-date="'+esc(x.date||"")+'"><strong>'+esc(x.date||"Date")+'</strong><span>'+esc(x.status||"Enquiry")+'</span><small>'+esc(x.note||"")+'</small></button>').join('')+'</div></section>';

  if(ok('enquiry')&&s.showEnquiry!==false)html+='<section id="enquiry" class="ew-section ew-enquiry"><div class="ew-enquiry-copy"><span class="ew-kicker">START PLANNING</span><h2>'+esc(d.enquiry?.heading||"Tell us about your celebration.")+'</h2><p>'+esc(d.enquiry?.text||"Share the essentials and we will take it from there.")+'</p><div class="ew-contact-links">'+(ok('call')&&c.phone?'<a href="tel:'+safe(c.phone)+'"><span>Call</span>'+esc(c.phone)+'</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'"><span>WhatsApp</span>Chat with planner</a>':'')+'</div></div><form id="ewLeadForm" class="ew-form"><div class="ew-form-grid"><label>Name<input name="name" required placeholder="Your name"></label><label>Phone<input name="phone" required type="tel" placeholder="+91"></label><label>Email<input name="email" type="email" placeholder="you@example.com"></label><label>Event Type<select name="eventType" id="ewEventType">'+eventTypes.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'<option>Other</option></select></label><label>Event Date<input name="eventDate" id="ewEventDate" type="date"></label><label>Location<input name="location" placeholder="City / venue / area"></label><label>Expected Guests<input name="guests" type="number" min="1" placeholder="e.g. 250"></label><label>Budget Range<select name="budget"><option>₹50,000 – ₹1 Lakh</option><option>₹1 – ₹2 Lakh</option><option>₹2 – ₹5 Lakh</option><option>₹5 Lakh+</option><option>Custom / Discuss</option></select></label><label>Package<select name="package" id="ewPackage"><option value="">Choose package</option>'+packages.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label class="full">Required Services<select name="services" id="ewServices" multiple size="5">'+services.map(x=>'<option value="'+esc(x.name)+'">'+esc(x.name)+'</option>').join('')+'</select><small class="ew-help">Use Ctrl / Cmd to select multiple services.</small></label></div><label>Message<textarea name="message" placeholder="Tell us about your theme, venue, family requirements or anything important"></textarea></label><button class="ew-btn solid" type="submit">'+esc(d.enquiry?.buttonText||"Send Enquiry on WhatsApp")+' <span>↗</span></button><p class="ew-form-note" id="ewLeadNotice"></p></form></section>';

  if(ok('reviews')&&s.showReviews!==false)html+='<section class="ew-section ew-reviews"><div class="ew-head"><span class="ew-kicker">CLIENT NOTES</span><h2>What clients remember about the planning experience.</h2></div><div class="ew-review-grid">'+reviews.map(x=>'<article>'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name||"Client")+'">':'')+'<div class="ew-stars">'+('★'.repeat(Math.max(1,Math.min(5,num(x.rating)||5))))+'</div><p>“'+esc(x.text||"")+'”</p><strong>'+esc(x.name||"Client")+'</strong><small>'+esc(x.event||"Event")+'</small></article>').join('')+'</div></section>';

  if(ok('about')&&s.showAbout!==false)html+='<section class="ew-section ew-about"><div class="ew-head split"><div><span class="ew-kicker">ABOUT THE STUDIO</span><h2>'+esc(b.about||"Tell your story here.")+'</h2></div><p>Build trust with a clear story, transparent planning process and practical event experience.</p></div><div class="ew-about-stats">'+list(d.aboutStats).map(x=>'<div><strong>'+esc(x.value||"")+'</strong><span>'+esc(x.label||"")+'</span></div>').join('')+'</div></section>';

  if(ok('team')&&s.showTeam!==false)html+='<section class="ew-section"><div class="ew-head"><span class="ew-kicker">PLANNING TEAM</span><h2>Meet the people behind the calm on event day.</h2></div><div class="ew-team-grid">'+team.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Planner")+'"><div><span>'+esc(x.role||"")+'</span><h3>'+esc(x.name||"Planner")+'</h3><p>'+esc(x.specialization||"")+'</p><small>'+esc(x.credentials||"")+'</small></div></article>').join('')+'</div></section>';

  if(ok('location')||ok('hours'))html+='<section class="ew-section ew-location"><div><span class="ew-kicker">STUDIO / OFFICE</span><h2>Let’s meet and talk through the celebration.</h2><p>'+esc(c.address||"Add your office address here.")+'</p><p>'+esc(c.hoursText||"")+'</p><div class="ew-actions">'+(ok('call')&&c.phone?'<a class="ew-btn solid" href="tel:'+safe(c.phone)+'">Call '+esc(c.phone)+'</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="ew-btn outline" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+'</div></div>'+(c.maps?'<a class="ew-map" target="_blank" href="'+esc(c.maps)+'"><span>OPEN MAP</span><strong>Studio location ↗</strong><small>'+esc(c.address||"View directions")+'</small></a>':'')+'</section>';

  if(ok('hours'))html+='<section class="ew-section ew-hours"><div class="ew-head"><span class="ew-kicker">CONTACT HOURS</span><h2>Reach the planning team.</h2></div><div class="ew-hours-list">'+hours.map(x=>'<div><strong>'+esc(x.day||"Day")+'</strong><span>'+esc(x.enabled!==false?(x.open||"")+" — "+(x.close||""):"Closed")+'</span></div>').join('')+'</div></section>';

  if(ok('social')&&s.showSocial!==false)html+='<section class="ew-section ew-social"><div><span class="ew-kicker">FOLLOW THE WORK</span><h2>See real celebrations, setups and behind-the-scenes planning.</h2></div><div class="ew-social-links">'+(d.social?.instagram?'<a class="ew-btn light" target="_blank" href="'+esc(d.social.instagram)+'">Instagram ↗</a>':'')+(d.social?.facebook?'<a class="ew-btn light" target="_blank" href="'+esc(d.social.facebook)+'">Facebook ↗</a>':'')+(d.social?.youtube?'<a class="ew-btn light" target="_blank" href="'+esc(d.social.youtube)+'">YouTube ↗</a>':'')+'</div></section>';

  if(ok('faq')&&s.showFAQ!==false)html+='<section class="ew-section"><div class="ew-head"><span class="ew-kicker">FAQ</span><h2>Before you book.</h2></div><div class="ew-faq">'+faq.map(x=>'<details><summary>'+esc(x.question||"Question")+'<span>+</span></summary><p>'+esc(x.answer||"")+'</p></details>').join('')+'</div></section>';

  if(ok('terms')||ok('privacy'))html+='<section class="ew-legal">'+(ok('terms')?'<details open><summary>Booking & Cancellation Terms</summary><p>'+esc(d.termsText||"")+'</p></details>':'')+(ok('privacy')?'<details><summary>Privacy Policy</summary><p>'+esc(d.privacyPolicy||"")+'</p></details>':'')+'</section>';

  html+='<footer class="ew-footer"><div><strong>'+esc(b.businessName||"Your Events Studio")+'</strong><span>'+esc(b.tagline||"")+'</span></div><div>'+(ok('call')&&c.phone?'<a href="tel:'+safe(c.phone)+'">Call</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">Email</a>':'')+'</div></footer>';
  if(ok('whatsapp')&&c.whatsapp)html+='<a class="ew-float-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp ↗</a>';
  return html+'</div>';
}
export function init(root,d={}){
  let selectedDate="";
  root.querySelectorAll('[data-event-type]').forEach(b=>b.addEventListener('click',()=>{const s=root.querySelector('#ewEventType');if(s)s.value=b.dataset.eventType||''}));
  root.querySelectorAll('[data-package]').forEach(b=>b.addEventListener('click',()=>{const s=root.querySelector('#ewPackage');if(s)s.value=b.dataset.package||''}));
  root.querySelectorAll('.ew-filter').forEach(b=>b.addEventListener('click',()=>{root.querySelectorAll('.ew-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const cat=b.dataset.galleryCat;root.querySelectorAll('[data-gallery-item]').forEach(x=>x.hidden=cat!=='all'&&x.dataset.galleryItem!==cat)}));
  root.querySelectorAll('[data-availability-date]').forEach(b=>b.addEventListener('click',()=>{selectedDate=b.dataset.availabilityDate||'';const f=root.querySelector('#ewEventDate');if(f){f.value=selectedDate;f.dispatchEvent(new Event('change'));}root.querySelector('#enquiry')?.scrollIntoView({behavior:'smooth'})}));
  const form=root.querySelector('#ewLeadForm');
  if(form)form.addEventListener('submit',ev=>{
    ev.preventDefault();
    const fd=new FormData(form),lead=Object.fromEntries(fd.entries());
    lead.services=[...form.querySelector('#ewServices')?.selectedOptions||[]].map(o=>o.value).join(', ');
    lead.status="New";lead.createdAt=new Date().toISOString();
    try{const state=Store.read(),data=structuredClone(state.data||d||{});data.leads=Array.isArray(data.leads)?data.leads:[];data.leads.unshift(lead);Store.update({data});const n=root.querySelector('#ewLeadNotice');if(n)n.textContent='Enquiry saved. The planning team can confirm date availability and next steps with you.';form.reset()}catch{const n=root.querySelector('#ewLeadNotice');if(n)n.textContent='Could not save the enquiry in this browser.'}
    const wa=d.contact?.whatsapp;
    if(wa){const msg=['Event enquiry',lead.name,lead.phone,lead.email,lead.eventType,lead.eventDate,lead.location,'Guests: '+lead.guests,'Budget: '+lead.budget,'Package: '+lead.package,'Services: '+lead.services,lead.message].filter(Boolean).join('\n');window.open('https://wa.me/'+safe(wa)+'?text='+encodeURIComponent(msg),'_blank')}
  });
}