const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/\D/g,'');
const money=v=>{const n=Number(v);return Number.isFinite(n)?'₹'+n.toLocaleString('en-IN'):String(v??'')};
export function render(d={},selected=[]){
  const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},ok=x=>selected.includes(x);
  const menu=(d.menu||[]).filter(x=>x.enabled!==false);
  const offers=(d.offers||[]).filter(x=>x.enabled!==false);
  const reviews=(d.reviews||[]).filter(x=>x.enabled!==false);
  return `<div class="site-preview restaurant-02">
    <header class="rp2-nav">
      <a class="rp2-brand" href="#top"><strong>${esc(b.businessName||'Your Restaurant')}</strong><small>${esc(b.tagline||'')}</small></a>
      <nav>${ok('menu')?'<a href="#menu">Menu</a>':''}${ok('offers')?'<a href="#offers">Offers</a>':''}${ok('reservation')?'<a href="#book">Book</a>':''}${ok('contact')?'<a href="#contact">Contact</a>':''}</nav>
      <div class="rp2-nav-actions">${ok('onlineOrder')?'<a class="rp2-cart-link" href="#cart">Cart <span data-cart-count>0</span></a>':''}<a class="template-admin-link" href="admin.html?template=restaurant-02">Admin</a></div>
    </header>
    ${ok('home')?`<section id="top" class="rp2-hero"><div class="rp2-hero-bg"></div><div class="rp2-hero-card"><span class="rp2-chip">GOOD FOOD · GOOD MOOD</span><small>${esc(b.ownerName||'KITCHEN TEAM')}</small><h1>${esc(h.title||'Eat bright. Order easy.')}</h1><p>${esc(h.text||'')}</p><div class="rp2-actions"><a class="rp2-btn pop" href="#menu">See the menu <i>→</i></a>${ok('reservation')?'<a class="rp2-btn light" href="#book">Book a table</a>':''}</div></div><div class="rp2-hero-photo"><img src="${esc(d.hero||'')}" alt=""></div></section>`:''}
    ${ok('about')&&s.showAbout!==false?`<section id="about" class="rp2-section rp2-about"><div class="rp2-kicker">OUR KITCHEN</div><div class="rp2-split"><h2>${esc(b.about||'')}</h2><div><span class="rp2-sticker">FRESH<br>DAILY</span><p>Easy to order, easy to share and made for busy city days.</p></div></div></section>`:''}
    ${ok('menu')&&s.showMenu!==false?`<section id="menu" class="rp2-section rp2-menu"><div class="rp2-heading"><div><div class="rp2-kicker">THE MENU</div><h2>Pick. Tap. Enjoy.</h2></div><p>Choose your favourites and send the order straight to WhatsApp.</p></div><div class="rp2-menu-grid">${menu.map((x,i)=>`<article class="rp2-dish" data-dish-id="${esc(x.id)}" data-price="${Number(x.price)||0}" data-name="${esc(x.name)}"><div class="dish-image"><img src="${esc(x.image||d.hero||'')}" alt="${esc(x.name)}"><span class="dish-no">0${i+1}</span></div><div class="dish-info"><span class="dish-cat">${esc(x.category||'')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'')}</p><div class="dish-bottom"><strong>${esc(x.displayPrice||money(x.price))}</strong>${ok('onlineOrder')?'<button class="rp2-add" type="button" data-add-dish>+ Add</button>':''}</div></div></article>`).join('')}</div></section>`:''}
    ${ok('offers')&&s.showOffers!==false?`<section id="offers" class="rp2-section rp2-offers"><div class="rp2-kicker">TODAY'S GOOD IDEA</div><h2>Specials worth sharing.</h2><div class="rp2-offer-grid">${offers.map(x=>`<article><span>✦</span><div><h3>${esc(x.title)}</h3><p>${esc(x.text||'')}</p></div></article>`).join('')}</div></section>`:''}
    ${ok('reviews')&&s.showReviews!==false?`<section class="rp2-section rp2-reviews"><div class="rp2-kicker">GUEST NOTES</div><h2>People came hungry.<br>They left smiling.</h2><div class="rp2-review-grid">${reviews.map(x=>`<article><b>${'★'.repeat(Number(x.rating)||0)}</b><p>“${esc(x.text||'')}”</p><strong>${esc(x.name||'Guest')}</strong></article>`).join('')}</div></section>`:''}
    ${ok('reservation')&&s.showReservation!==false?`<section id="book" class="rp2-section rp2-book"><div><div class="rp2-kicker">TABLE BOOKING</div><h2>Your table is a WhatsApp away.</h2><p>Pick a date, time and guest count. We'll send the request to the restaurant on WhatsApp.</p></div><form id="bookingForm" class="rp2-book-form"><input name="name" placeholder="Your name" required><input name="date" type="date" required><input name="time" type="time" required><input name="guests" type="number" min="1" max="50" value="2" required><button class="rp2-btn pop" type="submit">Book via WhatsApp <i>↗</i></button></form></section>`:''}
    ${ok('contact')&&s.showContact!==false?`<section id="contact" class="rp2-section rp2-contact"><div><div class="rp2-kicker">FIND US</div><h2>${esc(b.businessName||'Your Restaurant')}</h2><p>${esc(c.address||'')}</p></div><div class="rp2-actions">${c.maps&&ok('location')?'<a class="rp2-btn dark" target="_blank" href="'+esc(c.maps)+'">Directions</a>':''}${c.phone?'<a class="rp2-btn light" href="tel:'+esc(c.phone)+'">Call</a>':''}</div></section>`:''}
    ${ok('onlineOrder')?`<aside id="cart" class="rp2-cart" data-cart><div class="cart-head"><div><div class="rp2-kicker">YOUR ORDER</div><h3>WhatsApp cart</h3></div><button type="button" class="cart-close" data-cart-close>×</button></div><div data-cart-items class="cart-items"><p>Your cart is empty.</p></div><div class="cart-total"><span>Total</span><strong data-cart-total>₹0</strong></div><button type="button" class="rp2-btn pop full" data-whatsapp-order>Order on WhatsApp <i>↗</i></button></aside>`:''}
    <footer class="rp2-footer"><strong>${esc(b.businessName||'Your Restaurant')}</strong><span>${esc(b.tagline||'')}</span><a class="template-admin-link" href="admin.html?template=restaurant-02">Admin</a></footer>
  </div>`;
}
export function init(root,d={},selected=[]){
  const c=d.contact||{}, menu=(d.menu||[]).filter(x=>x.enabled!==false), ok=x=>selected.includes(x);
  const cart={}; const money=v=>'₹'+Number(v||0).toLocaleString('en-IN');
  const countEl=root.querySelector('[data-cart-count]'),itemsEl=root.querySelector('[data-cart-items]'),totalEl=root.querySelector('[data-cart-total]'),cartEl=root.querySelector('[data-cart]');
  const sync=()=>{const items=Object.values(cart),count=items.reduce((n,x)=>n+x.qty,0),total=items.reduce((n,x)=>n+x.qty*x.price,0);if(countEl)countEl.textContent=count;if(totalEl)totalEl.textContent=money(total);if(itemsEl)itemsEl.innerHTML=items.length?items.map(x=>`<div class="cart-row"><span><strong>${esc(x.name)}</strong><small>${x.qty} × ${money(x.price)}</small></span><div><button type="button" data-cart-minus="${esc(x.id)}">−</button><b>${x.qty}</b><button type="button" data-cart-plus="${esc(x.id)}">+</button></div></div>`).join(''):'<p>Your cart is empty.</p>'};
  root.querySelectorAll('[data-add-dish]').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('[data-dish-id]'),id=card?.dataset.dishId,x=menu.find(i=>i.id===id);if(!x)return;cart[id]=cart[id]||{id,name:x.name,price:Number(x.price)||0,qty:0};cart[id].qty++;btn.textContent='Added ✓';setTimeout(()=>btn.textContent='+ Add',700);sync();cartEl?.classList.add('open')}));
  root.addEventListener('click',e=>{const minus=e.target.closest('[data-cart-minus]'),plus=e.target.closest('[data-cart-plus]'),close=e.target.closest('[data-cart-close]');if(minus){const id=minus.dataset.cartMinus;if(cart[id])cart[id].qty--;if(cart[id]?.qty<=0)delete cart[id];sync()}if(plus){const id=plus.dataset.cartPlus;if(cart[id])cart[id].qty++;sync()}if(close)cartEl?.classList.remove('open')});
  root.querySelector('[data-whatsapp-order]')?.addEventListener('click',()=>{const items=Object.values(cart),total=items.reduce((n,x)=>n+x.qty*x.price,0);if(!items.length){alert('Please add at least one item to your cart.');return}const lines=items.map(x=>x.qty+' × '+x.name+' — '+money(x.qty*x.price));if(!safe(c.whatsapp)){alert('Please add a WhatsApp number in Admin > Contact.');return}const text='Hello '+(d.brand?.businessName||'Restaurant')+'!\n\nOrder:\n'+lines.join('\n')+'\n\nTotal: '+money(total);window.open('https://wa.me/'+safe(c.whatsapp)+'?text='+encodeURIComponent(text),'_blank')});
  root.querySelector('#bookingForm')?.addEventListener('submit',e=>{e.preventDefault();if(!safe(c.whatsapp)){alert('Please add a WhatsApp number in Admin > Contact.');return}const f=new FormData(e.currentTarget),text='Hello '+(d.brand?.businessName||'Restaurant')+'!\n\nTable booking request:\nName: '+f.get('name')+'\nDate: '+f.get('date')+'\nTime: '+f.get('time')+'\nGuests: '+f.get('guests');window.open('https://wa.me/'+safe(c.whatsapp)+'?text='+encodeURIComponent(text),'_blank')});
  sync();
}