const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function render(d={},selected=[]){
 const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},products=(d.products||[]).filter(x=>x.enabled!==false),reviews=(d.reviews||[]).filter(x=>x.enabled!==false),gallery=(d.gallery||[]).filter(x=>x.enabled!==false);
 const ok=x=>selected.includes(x),wa=String(c.whatsapp||'').replace(/\D/g,'');
 return '<div class="site-preview shop1"><header><strong>'+esc(b.businessName||'Your Store')+'</strong><nav>'+(ok('about')?'<a href="#about">About</a>':'')+(ok('products')?'<a href="#products">Shop</a>':'')+(ok('gallery')?'<a href="#gallery">Gallery</a>':'')+(ok('reviews')?'<a href="#reviews">Reviews</a>':'')+(ok('contact')?'<a href="#contact">Contact</a>':'')+'</nav><a class="template-admin-link" href="admin.html?template=ecommerce-01">Admin</a></header>'+
 (ok('home')?'<section class="hero"><img src="'+esc(d.hero||'')+'" alt=""><div><small>'+esc(b.ownerName||'ONLINE STORE')+'</small><h1>'+esc(h.title||'A storefront made for your products.')+'</h1><p>'+esc(h.text||'')+'</p></div></section>':'')+
 (ok('about')&&s.showAbout!==false?'<section id="about"><small>ABOUT</small><h2>'+esc(b.about||'A curated store with simple, trustworthy shopping.')+'</h2></section>':'')+
 (ok('products')?'<section id="products" class="soft"><small>SHOP</small><h2>Featured products</h2><div class="product-grid">'+products.map(x=>'<article class="product"><img src="'+esc(x.image||'')+'" alt=""><div><small>'+esc(x.category||'PRODUCT')+'</small><h3>'+esc(x.name||'Product')+'</h3><p>'+esc(x.description||'')+'</p><strong>'+esc(x.price||'Price on request')+'</strong>'+(ok('whatsapp')&&wa?'<a class="btn" target="_blank" href="https://wa.me/'+wa+'?text='+encodeURIComponent('Hi, I want to order '+(x.name||'this product'))+'">Order on WhatsApp</a>':'')+'</div></article>').join('')+'</div></section>':'')+
 (ok('gallery')&&s.showGallery!==false?'<section id="gallery"><small>GALLERY</small><div class="gallery">'+gallery.map(x=>'<figure><img src="'+esc(x.image||'')+'" alt=""><figcaption>'+esc(x.title||'')+'</figcaption></figure>').join('')+'</div></section>':'')+
 (ok('reviews')&&s.showReviews!==false?'<section id="reviews" class="soft"><small>REVIEWS</small><div class="grid">'+reviews.map(x=>'<article><b>'+('★'.repeat(Number(x.rating)||0))+'</b><p>“'+esc(x.text||'')+'”</p><strong>'+esc(x.name||'Customer')+'</strong></article>').join('')+'</div></section>':'')+
 (ok('contact')&&s.showContact!==false?'<section id="contact"><small>CONTACT</small><h2>Need help choosing?</h2><p>'+esc(c.call||'')+' · '+esc(c.location||'')+'</p><div>'+(ok('location')&&c.maps?'<a class="btn dark" target="_blank" href="'+esc(c.maps)+'">Directions</a>':'')+(ok('whatsapp')&&wa?'<a class="btn" target="_blank" href="https://wa.me/'+wa+'">WhatsApp</a>':'')+'</div></section>':'')+
 '<footer>© '+new Date().getFullYear()+' '+esc(b.businessName||'Your Store')+'</footer></div>';
}