const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function render(d={},selected=[]){
 const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},services=(d.services||[]).filter(x=>x.enabled!==false),rashis=(d.rashis||[]).filter(x=>x.enabled!==false),reviews=(d.reviews||[]).filter(x=>x.enabled!==false),faqs=(d.faqs||[]).filter(x=>x.enabled!==false);
 const ok=x=>selected.includes(x),wa=String(c.whatsapp||'').replace(/\D/g,'');
 return '<div class="site-preview astro1"><header><strong>'+esc(b.businessName||'Your Astrology Studio')+'</strong><nav>'+(ok('about')?'<a href="#about">About</a>':'')+(ok('services')?'<a href="#services">Services</a>':'')+(ok('rashis')?'<a href="#rashis">Rashi</a>':'')+(ok('reviews')?'<a href="#reviews">Reviews</a>':'')+(ok('contact')?'<a href="#contact">Contact</a>':'')+'</nav><a class="template-admin-link" href="admin.html?template=astrology-01">Admin</a></header>'+
 (ok('home')?'<section class="hero"><img src="'+esc(d.hero||'')+'" alt=""><div><small>'+esc(b.ownerName||'ASTROLOGY & GUIDANCE')+'</small><h1>'+esc(h.title||'Guidance for every important chapter.')+'</h1><p>'+esc(h.text||'')+'</p>'+(ok('whatsapp')&&wa?'<a class="btn" target="_blank" href="https://wa.me/'+wa+'">WhatsApp</a>':'')+'</div></section>':'')+
 (ok('about')&&s.showAbout!==false?'<section id="about"><small>ABOUT</small><h2>'+esc(b.about||'Vedic guidance rooted in practical life decisions.')+'</h2></section>':'')+
 (ok('services')&&s.showServices!==false?'<section id="services" class="soft"><small>SERVICES</small><h2>Astrology services</h2><div class="grid">'+services.map(x=>'<article><h3>'+esc(x.name)+'</h3><strong>'+esc(x.price||'')+'</strong><p>'+esc(x.description||'')+'</p></article>').join('')+'</div></section>':'')+
 (ok('rashis')?'<section id="rashis"><small>RASHI</small><h2>Explore the 12 signs</h2><div class="rashi-grid">'+rashis.map(x=>'<article><b>'+esc(x.symbol||'✦')+'</b><h3>'+esc(x.name||'Rashi')+'</h3><p>'+esc(x.description||'')+'</p></article>').join('')+'</div></section>':'')+
 (ok('reviews')&&s.showReviews!==false?'<section id="reviews" class="soft"><small>CLIENT EXPERIENCES</small><div class="grid">'+reviews.map(x=>'<article><b>'+('★'.repeat(Number(x.rating)||0))+'</b><p>“'+esc(x.text||'')+'”</p><strong>'+esc(x.name||'Client')+'</strong></article>').join('')+'</div></section>':'')+
 (ok('faq')?'<section><small>FAQ</small>'+faqs.map(x=>'<details><summary>'+esc(x.question)+'</summary><p>'+esc(x.answer)+'</p></details>').join('')+'</section>':'')+
 (ok('contact')&&s.showContact!==false?'<section id="contact"><small>CONTACT</small><h2>Book a consultation.</h2><p>'+esc(c.call||'')+' · '+esc(c.location||'')+'</p><div>'+(ok('location')&&c.maps?'<a class="btn dark" target="_blank" href="'+esc(c.maps)+'">Directions</a>':'')+(ok('whatsapp')&&wa?'<a class="btn" target="_blank" href="https://wa.me/'+wa+'">WhatsApp</a>':'')+'</div></section>':'')+
 '<footer>© '+new Date().getFullYear()+' '+esc(b.businessName||'Your Astrology Studio')+'</footer></div>';
}