const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const list=v=>Array.isArray(v)?v.filter(x=>x&&x.enabled!==false):[];
export function render(d={},selected=[]){
  const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},ok=x=>selected.includes(x);
  const courses=list(d.courses),fees=list(d.fees),batches=list(d.batches),faculty=list(d.faculty),results=list(d.results),stories=list(d.stories),resources=list(d.resources),facilities=list(d.facilities),reviews=list(d.reviews),faq=list(d.faq);
  const categories=[...new Set(courses.map(x=>x.category).filter(Boolean))];
  let html='<div class="site-preview coaching-education-01">';
  html+='<header class="ed-nav"><a class="ed-brand" href="#home"><span class="ed-mark">NS</span><span><strong>'+esc(b.businessName||"Your Academy")+'</strong><small>'+esc(b.tagline||"LEARNING · COACHING · MENTORING")+'</small></span></a><nav>';
  if(ok('home'))html+='<a href="#home">Home</a>';if(ok('courses'))html+='<a href="#courses">Courses</a>';if(ok('fees'))html+='<a href="#fees">Fees</a>';if(ok('batches'))html+='<a href="#batches">Batches</a>';if(ok('faculty'))html+='<a href="#faculty">Faculty</a>';if(ok('demo'))html+='<a href="#demo">Demo</a>';if(ok('admission'))html+='<a href="#admission">Admission</a>';
  html+='</nav><div class="ed-nav-actions">'+(ok('whatsapp')&&c.whatsapp?'<a class="ed-mini ed-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+(ok('call')&&c.phone?'<a class="ed-mini" href="tel:'+safe(c.phone)+'">Call</a>':'')+'<a class="template-admin-link" href="admin.html?template=coaching-education-01">Admin</a></div></header>';

  if(ok('home')&&s.showHome!==false)html+='<section id="home" class="ed-hero"><div class="ed-hero-copy"><span class="ed-kicker">COACHING · TUITION · SKILLS</span><h1>'+esc(h.title||"Turn your learning goals into a clear plan.")+'</h1><p>'+esc(h.text||"Structured learning with experienced mentors.")+'</p><div class="ed-actions">'+(ok('demo')?'<a class="ed-btn solid" href="#demo">Book Free Demo <span>↗</span></a>':'')+(ok('admission')?'<a class="ed-btn light" href="#admission">Talk to a Counsellor</a>':'')+'</div><div class="ed-stats"><div><strong>'+esc(b.students||0)+'+</strong><span>students guided</span></div><div><strong>'+esc(b.foundedYear||"")+'</strong><span>founded</span></div><div><strong>Online + Offline</strong><span>learning options</span></div></div></div><div class="ed-hero-media">'+(d.heroVideo?'<video autoplay muted loop playsinline poster="'+esc(d.hero||"")+'"><source src="'+esc(d.heroVideo)+'" type="video/mp4"></video>':'<img src="'+esc(d.hero||"")+'" alt="'+esc(b.businessName||"Academy")+'">')+'<div class="ed-hero-chip"><span>LEARNING NOTE</span><strong>Understand first.<br>Perform with confidence.</strong></div></div></section>';

  if(ok('courses')&&s.showCourses!==false)html+='<section id="courses" class="ed-section"><div class="ed-head split"><div><span class="ed-kicker">COURSES & PROGRAMS</span><h2>Choose the learning path that fits the goal.</h2></div><p>Use the category filters to present competitive exams, school support and skill-development programs.</p></div><div class="ed-filter-row"><button class="ed-filter active" data-course-cat="all">All</button>'+categories.map(x=>'<button class="ed-filter" data-course-cat="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><div class="ed-course-grid">'+courses.map(x=>'<article data-course-item="'+esc(x.category||"Other")+'"><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Course")+'"><div class="ed-course-body"><div class="ed-course-meta"><span>'+esc(x.category||"Program")+'</span><span>'+esc(x.format||"")+'</span></div><h3>'+esc(x.name||"Course")+'</h3><p>'+esc(x.summary||"")+'</p><div class="ed-course-foot"><strong>'+esc(x.price||"Enquire")+'</strong><button type="button" data-course-select="'+esc(x.name||"")+'">Enquire ↗</button></div></div></article>').join('')+'</div></section>';

  if(ok('courseDetails')&&s.showCourseDetails!==false)html+='<section class="ed-section ed-details"><div class="ed-head split"><div><span class="ed-kicker">COURSE DETAILS</span><h2>Syllabus, level, duration and format — visible before the enquiry.</h2></div><p>Keep this information current in Admin so students and parents can understand the program scope.</p></div><div class="ed-course-detail-grid">'+courses.map(x=>'<article><div><span>'+esc(x.category||"")+'</span><h3>'+esc(x.name||"Course")+'</h3><small>'+esc(x.level||"")+" · "+esc(x.duration||"")+" · "+esc(x.format||"")+'</small></div><ul>'+((Array.isArray(x.syllabus)?x.syllabus:String(x.syllabus||"").split("\n").filter(Boolean))).map(v=>'<li>✓ '+esc(v)+'</li>').join('')+'</ul></article>').join('')+'</div></section>';

  if(ok('fees')&&s.showFees!==false)html+='<section id="fees" class="ed-section ed-fees"><div class="ed-head split"><div><span class="ed-kicker">FEE PLANS</span><h2>Compare the study support included in each plan.</h2></div><p>Displayed fees are sample starting prices. Confirm current fees, discounts, registration charges and payment schedules with the institute.</p></div><div class="ed-fee-grid">'+fees.map((x,i)=>'<article class="'+(x.tier==="Elite"?'featured':'')+'"><div class="ed-fee-top"><span>'+esc(x.tier||"Plan")+'</span><small>0'+(i+1)+'</small></div><h3>'+esc(x.name||"Fee plan")+'</h3><strong>'+esc(x.price||"Enquire")+'</strong><em>'+esc(x.billing||"")+' · '+esc(x.bestFor||"")+'</em><ul>'+((Array.isArray(x.includes)?x.includes:String(x.includes||"").split("\n").filter(Boolean))).map(v=>'<li>✓ '+esc(v)+'</li>').join('')+'</ul><a class="ed-btn '+(x.tier==="Elite"?'solid':'outline')+'" href="#admission" data-fee-plan="'+esc(x.name||"")+'">Ask about this plan <span>↗</span></a></article>').join('')+'</div></section>';

  if(ok('batches')&&s.showBatches!==false)html+='<section id="batches" class="ed-section ed-batches"><div class="ed-head split"><div><span class="ed-kicker">BATCH TIMINGS & SEATS</span><h2>See when the next learning slot runs.</h2></div><p>Seat counters are planning information only. The institute should confirm final availability before admission.</p></div><div class="ed-batch-table"><div class="ed-batch-row ed-batch-head"><span>Day</span><span>Time</span><span>Course</span><span>Faculty</span><span>Mode</span><span>Seats</span></div>'+batches.map(x=>'<button type="button" class="ed-batch-row" data-batch="'+esc(x.course||"")+'"><span>'+esc(x.day||"")+'</span><span>'+esc(x.time||"")+'</span><span><strong>'+esc(x.course||"")+'</strong></span><span>'+esc(x.faculty||"")+'</span><span>'+esc(x.mode||"")+'</span><span><b>'+num(x.seatsLeft)+'</b> / '+num(x.seatsTotal)+' · '+esc(x.status||"")+'</span></button>').join('')+'</div></section>';

  if(ok('faculty')&&s.showFaculty!==false)html+='<section id="faculty" class="ed-section ed-faculty"><div class="ed-head"><span class="ed-kicker">FACULTY & MENTORS</span><h2>Meet the people guiding the learning journey.</h2></div><div class="ed-faculty-grid">'+faculty.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Faculty")+'"><div><span>'+esc(x.role||"")+'</span><h3>'+esc(x.name||"Mentor")+'</h3><p>'+esc(x.specialization||"")+'</p><small>'+esc(x.credentials||"")+'</small></div></article>').join('')+'</div></section>';

  if(ok('demo')&&s.showDemo!==false)html+='<section id="demo" class="ed-section ed-demo"><div><span class="ed-kicker">FREE DEMO CLASS</span><h2>'+esc(d.demoClass?.heading||"Try a free demo class.")+'</h2><p>'+esc(d.demoClass?.text||"Choose a course and preferred slot.")+'</p></div><form id="edDemoForm" class="ed-form compact"><label>Name<input name="name" required placeholder="Student / parent name"></label><label>Phone<input name="phone" required type="tel" placeholder="+91"></label><label>Course<select name="course" id="edDemoCourse">'+courses.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label>Preferred batch<select name="preferredBatch"><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Weekend</option></select></label><button class="ed-btn solid" type="submit">'+esc(d.demoClass?.buttonText||"Book Free Demo")+' <span>↗</span></button><p id="edDemoNotice"></p></form></section>';

  if(ok('admission')&&s.showAdmission!==false)html+='<section id="admission" class="ed-section ed-admission"><div class="ed-admission-copy"><span class="ed-kicker">ADMISSION / COUNSELLING</span><h2>'+esc(d.admission?.heading||"Talk to an academic counsellor.")+'</h2><p>'+esc(d.admission?.text||"Share the learner's goals and preferred program.")+'</p><div class="ed-contact-links">'+(ok('call')&&c.phone?'<a href="tel:'+safe(c.phone)+'"><span>Call</span>'+esc(c.phone)+'</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'"><span>WhatsApp</span>Chat with counsellor</a>':'')+'</div></div><form id="edAdmissionForm" class="ed-form"><div class="ed-form-grid"><label>Name<input name="name" required placeholder="Student / parent name"></label><label>Phone<input name="phone" required type="tel" placeholder="+91"></label><label>Email<input name="email" type="email" placeholder="you@example.com"></label><label>Course<select name="course" id="edAdmissionCourse">'+courses.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label>Class / Level<input name="classLevel" placeholder="Class 10 / 12 / Graduate"></label><label>Preferred Batch<select name="preferredBatch"><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Weekend</option><option>Flexible</option></select></label><label>Mode<select name="mode"><option>Classroom</option><option>Online</option><option>Hybrid</option></select></label><label>Budget Range<select name="budget"><option>Under ₹10,000</option><option>₹10,000 – ₹25,000</option><option>₹25,000 – ₹50,000</option><option>₹50,000+</option><option>Discuss</option></select></label><label>Location<input name="location" placeholder="Area / City"></label></div><label>Message<textarea name="message" placeholder="Target exam, subjects, learning goal, preferred timing or other details"></textarea></label><button class="ed-btn solid" type="submit">'+esc(d.admission?.buttonText||"Request Admission Info")+' <span>↗</span></button><p id="edAdmissionNotice"></p></form></section>';

  if(ok('results')&&s.showResults!==false)html+='<section class="ed-section ed-results"><div class="ed-head"><span class="ed-kicker">RESULTS & ACHIEVEMENTS</span><h2>Use verified numbers to show your institute’s learning record.</h2></div><div class="ed-result-grid">'+results.map(x=>'<article><strong>'+esc(x.value||"")+'</strong><h3>'+esc(x.title||"Achievement")+'</h3><p>'+esc(x.caption||"")+'</p></article>').join('')+'</div></section>';

  if(ok('studentStories')&&s.showStudentStories!==false)html+='<section class="ed-section"><div class="ed-head"><span class="ed-kicker">STUDENT STORIES</span><h2>Real learning experiences from students and families.</h2></div><div class="ed-story-grid">'+stories.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Student")+'"><div><span>'+esc(x.course||"Course")+'</span><p>“'+esc(x.quote||"")+'”</p><strong>'+esc(x.name||"Student")+'</strong></div></article>').join('')+'</div></section>';

  if(ok('resources')&&s.showResources!==false)html+='<section class="ed-section ed-resources"><div class="ed-head split"><div><span class="ed-kicker">STUDY RESOURCES</span><h2>Give prospective students a useful next step.</h2></div><p>Link your real worksheets, mock tests, guides and orientation videos here.</p></div><div class="ed-resource-grid">'+resources.map(x=>'<a target="_blank" href="'+esc(x.url||"#")+'"><span>'+esc(x.type||"Resource")+'</span><strong>'+esc(x.title||"Resource")+'</strong><p>'+esc(x.description||"")+'</p><b>Open ↗</b></a>').join('')+'</div></section>';

  if(ok('facilities')&&s.showFacilities!==false)html+='<section class="ed-section ed-facilities"><div class="ed-head"><span class="ed-kicker">CAMPUS & FACILITIES</span><h2>Show the learning environment behind the program.</h2></div><div class="ed-facility-grid">'+facilities.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.title||"Facility")+'"><div><h3>'+esc(x.title||"Facility")+'</h3><p>'+esc(x.text||"")+'</p></div></article>').join('')+'</div></section>';

  if(ok('reviews')&&s.showReviews!==false)html+='<section class="ed-section ed-reviews"><div class="ed-head"><span class="ed-kicker">STUDENT & PARENT REVIEWS</span><h2>What families say about the learning experience.</h2></div><div class="ed-review-grid">'+reviews.map(x=>'<article>'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name||"Reviewer")+'">':'')+'<div class="ed-stars">'+('★'.repeat(Math.max(1,Math.min(5,num(x.rating)||5))))+'</div><p>“'+esc(x.text||"")+'”</p><strong>'+esc(x.name||"Reviewer")+'</strong><small>'+esc(x.type||"Student")+'</small></article>').join('')+'</div></section>';

  if(ok('about')&&s.showAbout!==false)html+='<section class="ed-section ed-about"><div class="ed-head split"><div><span class="ed-kicker">ABOUT THE INSTITUTE</span><h2>'+esc(b.about||"Tell the institute story here.")+'</h2></div><p>Explain your teaching approach, mentor access, learning philosophy and what families can expect.</p></div><div class="ed-about-stats"><div><strong>'+esc(b.foundedYear||"")+'</strong><span>founded</span></div><div><strong>'+esc(b.students||0)+'+</strong><span>students guided</span></div><div><strong>'+courses.length+'</strong><span>active programs</span></div></div></section>';

  if(ok('faq')&&s.showFAQ!==false)html+='<section class="ed-section"><div class="ed-head"><span class="ed-kicker">FAQ</span><h2>Before you enrol.</h2></div><div class="ed-faq">'+faq.map(x=>'<details><summary>'+esc(x.question||"Question")+'<span>+</span></summary><p>'+esc(x.answer||"")+'</p></details>').join('')+'</div></section>';

  if(ok('location')||ok('hours'))html+='<section class="ed-section ed-location"><div><span class="ed-kicker">VISIT / COUNSELLING</span><h2>'+esc(b.businessName||"Your Academy")+'</h2><p>'+esc(c.address||"Add institute address here.")+'</p><p>'+esc(c.hoursText||"")+'</p><div class="ed-actions">'+(ok('call')&&c.phone?'<a class="ed-btn solid" href="tel:'+safe(c.phone)+'">Call</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="ed-btn outline" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+'</div></div>'+(c.maps?'<a class="ed-map" target="_blank" href="'+esc(c.maps)+'"><span>OPEN MAP</span><strong>Get directions ↗</strong><small>'+esc(c.address||"Institute location")+'</small></a>':'')+'</section>';

  if(ok('hours'))html+='<section class="ed-section ed-hours"><div class="ed-head"><span class="ed-kicker">OFFICE HOURS</span><h2>Talk to the team during counselling hours.</h2></div><div class="ed-hours-list"><div><strong>Weekdays</strong><span>'+esc(d.hours?.weekdays||"")+'</span></div><div><strong>Weekends</strong><span>'+esc(d.hours?.weekends||"")+'</span></div></div></section>';

  if(ok('terms')||ok('privacy'))html+='<section class="ed-legal">'+(ok('terms')?'<details open><summary>Terms & Admission Policy</summary><p>'+esc(d.termsText||"")+'</p></details>':'')+(ok('privacy')?'<details><summary>Privacy Policy</summary><p>'+esc(d.privacyPolicy||"")+'</p></details>':'')+'</section>';

  html+='<footer class="ed-footer"><div><strong>'+esc(b.businessName||"Your Academy")+'</strong><span>'+esc(b.tagline||"")+'</span></div><div>'+(ok('call')&&c.phone?'<a href="tel:'+safe(c.phone)+'">Call</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">Email</a>':'')+'</div></footer>';
  if(ok('whatsapp')&&c.whatsapp)html+='<a class="ed-float-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp ↗</a>';
  return html+'</div>';
}
export function init(root,d={}){
  const setSelect=(selector,value)=>{const e=root.querySelector(selector);if(e&&value)e.value=value};
  root.querySelectorAll('[data-course-select]').forEach(b=>b.onclick=()=>{setSelect('#edAdmissionCourse',b.dataset.courseSelect);root.querySelector('#admission')?.scrollIntoView({behavior:"smooth"})});
  root.querySelectorAll('[data-fee-plan]').forEach(b=>b.onclick=()=>{root.querySelector('#admission')?.scrollIntoView({behavior:"smooth"});setTimeout(()=>{const e=root.querySelector('#edAdmissionForm textarea[name="message"]');if(e)e.value='Interested in: '+(b.dataset.feePlan||'')},50)});
  root.querySelectorAll('[data-batch]').forEach(b=>b.onclick=()=>{setSelect('#edDemoCourse',b.dataset.batch);setSelect('#edAdmissionCourse',b.dataset.batch);root.querySelector('#demo')?.scrollIntoView({behavior:"smooth"})});
  root.querySelectorAll('.ed-filter').forEach(b=>b.onclick=()=>{root.querySelectorAll('.ed-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const cat=b.dataset.courseCat;root.querySelectorAll('[data-course-item]').forEach(x=>x.hidden=cat!=='all'&&x.dataset.courseItem!==cat)});
  const saveLead=(lead,noticeSelector,form)=>{
    lead.status="New";lead.createdAt=new Date().toISOString();
    try{const state=Store.read(),data=structuredClone(state.data||d||{});data.leads=Array.isArray(data.leads)?data.leads:[];data.leads.unshift(lead);Store.update({data});const n=root.querySelector(noticeSelector);if(n)n.textContent="Request saved. The academy team can confirm the next step with you.";form.reset()}catch{const n=root.querySelector(noticeSelector);if(n)n.textContent="Could not save this request in the browser."}
    const wa=d.contact?.whatsapp;
    if(wa){const msg=['Education enquiry',lead.leadType,lead.name,lead.phone,lead.email,lead.course,lead.classLevel,lead.preferredBatch,lead.mode,lead.budget,lead.location,lead.message].filter(Boolean).join("\n");window.open('https://wa.me/'+safe(wa)+'?text='+encodeURIComponent(msg),'_blank')}
  };
  const df=root.querySelector('#edDemoForm');if(df)df.addEventListener('submit',e=>{e.preventDefault();const lead=Object.fromEntries(new FormData(df).entries());lead.leadType="Free Demo";saveLead(lead,'#edDemoNotice',df)});
  const af=root.querySelector('#edAdmissionForm');if(af)af.addEventListener('submit',e=>{e.preventDefault();const lead=Object.fromEntries(new FormData(af).entries());lead.leadType="Admission";saveLead(lead,'#edAdmissionNotice',af)});
}