const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const list=v=>Array.isArray(v)?v.filter(x=>x&&x.enabled!==false):[];
const typeLabel=t=>({School:"School",College:"College",Coaching:"Coaching Institute","Coaching Institute":"Coaching Institute","Training Institute":"Training Institute"}[t]||"Educational Institute");
const typeConfig=t=>{
  const type=String(t||"School");
  if(type==="School") return {hero:"Shape curious minds. Build confident futures.",kicker:"SCHOOL · LEARNING · COMMUNITY",primary:"Explore Admissions",secondary:"Book a Campus Visit",courseWord:"Academic Programs",facultyWord:"Teachers",leadLabel:"Admission / Campus Visit",hide:["placements"],badge:"2026–27 Admissions"};
  if(type==="College") return {hero:"Build knowledge. Discover opportunity. Find your direction.",kicker:"COLLEGE · ACADEMICS · CAMPUS LIFE",primary:"Explore Programs",secondary:"Request Admission Info",courseWord:"Degree Programs",facultyWord:"Faculty & HODs",leadLabel:"College Admission",hide:[],badge:"Admissions & Applications"};
  if(type==="Training Institute") return {hero:"Learn the skill. Build the portfolio. Move forward.",kicker:"TRAINING · SKILLS · CAREER",primary:"Explore Courses",secondary:"Book Free Demo",courseWord:"Training Programs",facultyWord:"Trainers & Mentors",leadLabel:"Training Enquiry",hide:[],badge:"New Batches Open"};
  return {hero:"Turn learning goals into a clear plan.",kicker:"COACHING · TUITION · MENTORING",primary:"Explore Courses",secondary:"Book Free Demo",courseWord:"Courses & Programs",facultyWord:"Faculty & Mentors",leadLabel:"Coaching Enquiry",hide:["campusLife","transport","departments"],badge:"New Batches Open"};
};
export function render(d={},selected=[]){
 const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},edu=d.education||{},typ=String(edu.type||"School"),cfg=typeConfig(typ),ok=x=>selected.includes(x)&&s["show"+x.charAt(0).toUpperCase()+x.slice(1)]!==false;
 const courses=list(d.courses),fees=list(d.fees),batches=list(d.batches),faculty=list(d.faculty),results=list(d.results),stories=list(d.stories),resources=list(d.resources),facilities=list(d.facilities),reviews=list(d.reviews),faq=list(d.faq),departments=list(d.departments),placements=list(d.placements),campusLife=list(d.campusLife),notices=list(d.notices),calendar=list(d.calendar),transport=list(d.transport);
 const visible=(id)=>selected.includes(id)&&s["show"+id.charAt(0).toUpperCase()+id.slice(1)]!==false&&!cfg.hide.includes(id);
 const categories=[...new Set(courses.map(x=>x.category).filter(Boolean))];
 let html='<div class="site-preview coaching-education-01 '+typ.toLowerCase().replace(/[^a-z]+/g,"-")+'">';
 html+='<header class="ed-nav"><a class="ed-brand" href="#home"><span class="ed-mark">'+(typ==="School"?"EDU":typ==="College"?"UNI":typ==="Training Institute"?"SKL":"ACD")+'</span><span><strong>'+esc(b.businessName||"Your Institute")+'</strong><small>'+esc(typeLabel(typ))+' · '+esc(b.tagline||"LEARNING · GROWTH · FUTURE")+'</small></span></a><nav>';
 for(const [id,label] of [["home","Home"],["academics",cfg.courseWord],["fees","Fees"],["faculty",cfg.facultyWord],["admission","Admission"],["campusLife","Campus Life"]]) if(visible(id)) html+='<a href="#'+id+'">'+esc(label)+'</a>';
 html+='</nav><div class="ed-nav-actions">'+(visible("whatsapp")&&c.whatsapp?'<a class="ed-mini ed-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+(c.phone?'<a class="ed-mini" href="tel:'+safe(c.phone)+'">Call</a>':'')+'<a class="template-admin-link" href="admin.html?template=coaching-education-01">Admin</a></div></header>';
 if(visible("home")) html+='<section id="home" class="ed-hero"><div class="ed-hero-copy"><span class="ed-kicker">'+esc(cfg.kicker)+'</span><div class="ed-type-pill">'+esc(typ)+' · '+esc(cfg.badge)+'</div><h1>'+esc(h.title||cfg.hero)+'</h1><p>'+esc(h.text||"Structured learning, experienced educators and clear next steps for students and families.")+'</p><div class="ed-actions">'+(visible("admission")?'<a class="ed-btn solid" href="#admission">'+esc(cfg.primary)+' <span>↗</span></a>':'')+(visible("demo")?'<a class="ed-btn light" href="#demo">'+esc(cfg.secondary)+'</a>':'')+'</div><div class="ed-stats"><div><strong>'+esc(b.students||0)+'+</strong><span>learners connected</span></div><div><strong>'+esc(b.foundedYear||"")+'</strong><span>founded</span></div><div><strong>'+esc(typ)+'</strong><span>education model</span></div></div></div><div class="ed-hero-media">'+(d.heroVideo?'<video autoplay muted loop playsinline poster="'+esc(d.hero||"")+'"><source src="'+esc(d.heroVideo)+'" type="video/mp4"></video>':'<img src="'+esc(d.hero||"")+'" alt="'+esc(b.businessName||"Educational institution")+'">')+'<div class="ed-hero-chip"><span>'+esc(typeLabel(typ).toUpperCase())+'</span><strong>'+esc(typ==="College"?d.college?.accreditation||"Programs · Departments · Campus":typ==="School"?d.school?.curriculum||"Classes · Curriculum · Community":cfg.hero)+'</strong></div></div></section>';
 if(visible("academics")) html+='<section id="academics" class="ed-section"><div class="ed-head split"><div><span class="ed-kicker">'+esc(cfg.courseWord.toUpperCase())+'</span><h2>Find the program that matches the learner’s next step.</h2></div><p>Use category filters to separate school programs, degree programs, coaching courses or skill training.</p></div><div class="ed-filter-row"><button class="ed-filter active" data-course-cat="all">All</button>'+categories.map(x=>'<button class="ed-filter" data-course-cat="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><div class="ed-course-grid">'+courses.map(x=>'<article data-course-item="'+esc(x.category||"Other")+'"><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Program")+'"><div class="ed-course-body"><div class="ed-course-meta"><span>'+esc(x.category||"Program")+'</span><span>'+esc(x.format||"")+'</span></div><h3>'+esc(x.name||"Program")+'</h3><p>'+esc(x.summary||"")+'</p><div class="ed-course-foot"><strong>'+esc(x.price||"Enquire")+'</strong><button type="button" data-course-select="'+esc(x.name||"")+'">Enquire ↗</button></div></div></article>').join('')+'</div></section>';
 if(visible("courseDetails")) html+='<section id="courseDetails" class="ed-section ed-details"><div class="ed-head split"><div><span class="ed-kicker">PROGRAM DETAILS</span><h2>Level, duration, format and syllabus — visible before the enquiry.</h2></div><p>Keep official program details, subject structure and current fees updated from Admin.</p></div><div class="ed-course-detail-grid">'+courses.map(x=>'<article><div><span>'+esc(x.category||"")+'</span><h3>'+esc(x.name||"Program")+'</h3><small>'+esc(x.level||"")+" · "+esc(x.duration||"")+" · "+esc(x.format||"")+'</small></div><ul>'+((Array.isArray(x.syllabus)?x.syllabus:String(x.syllabus||"").split("\\n").filter(Boolean))).map(v=>'<li>✓ '+esc(v)+'</li>').join('')+'</ul></article>').join('')+'</div></section>';
 if(visible("fees")) html+='<section id="fees" class="ed-section ed-fees"><div class="ed-head split"><div><span class="ed-kicker">FEES / TUITION</span><h2>Show the support included at each fee level.</h2></div><p>Replace sample prices with your official tuition, registration, discounts, taxes and payment schedule.</p></div><div class="ed-fee-grid">'+fees.map((x,i)=>'<article class="'+(i===1?'featured':'')+'"><div class="ed-fee-top"><span>'+esc(x.tier||"Plan")+'</span><small>0'+(i+1)+'</small></div><h3>'+esc(x.name||"Fee plan")+'</h3><strong>'+esc(x.price||"Enquire")+'</strong><em>'+esc(x.billing||"")+' · '+esc(x.bestFor||"")+'</em><ul>'+((Array.isArray(x.includes)?x.includes:String(x.includes||"").split("\\n").filter(Boolean))).map(v=>'<li>✓ '+esc(v)+'</li>').join('')+'</ul><a class="ed-btn '+(i===1?'solid':'outline')+'" href="#admission" data-fee-plan="'+esc(x.name||"")+'">Ask about this <span>↗</span></a></article>').join('')+'</div></section>';
 if(visible("batches")) html+='<section id="batches" class="ed-section ed-batches"><div class="ed-head split"><div><span class="ed-kicker">TIMINGS & AVAILABILITY</span><h2>See class, batch or session timing at a glance.</h2></div><p>Final availability should always be confirmed by the institution.</p></div><div class="ed-batch-table"><div class="ed-batch-row ed-batch-head"><span>Day</span><span>Time</span><span>Program</span><span>Faculty</span><span>Mode</span><span>Seats</span></div>'+batches.map(x=>'<button type="button" class="ed-batch-row" data-batch="'+esc(x.course||"")+'"><span>'+esc(x.day||"")+'</span><span>'+esc(x.time||"")+'</span><span><strong>'+esc(x.course||"")+'</strong></span><span>'+esc(x.faculty||"")+'</span><span>'+esc(x.mode||"")+'</span><span><b>'+num(x.seatsLeft)+'</b> / '+num(x.seatsTotal)+' · '+esc(x.status||"")+'</span></button>').join('')+'</div></section>';
 if(visible("faculty")) html+='<section id="faculty" class="ed-section ed-faculty"><div class="ed-head"><span class="ed-kicker">'+esc(cfg.facultyWord.toUpperCase())+'</span><h2>Meet the educators guiding the learning journey.</h2></div><div class="ed-faculty-grid">'+faculty.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Faculty")+'"><div><span>'+esc(x.role||"")+'</span><h3>'+esc(x.name||"Educator")+'</h3><p>'+esc(x.specialization||"")+'</p><small>'+esc(x.credentials||"")+'</small></div></article>').join('')+'</div></section>';
 if(visible("demo")) html+='<section id="demo" class="ed-section ed-demo"><div><span class="ed-kicker">'+(typ==="School"?"CAMPUS VISIT / ENQUIRY":"FREE DEMO")+'</span><h2>'+esc(d.demoClass?.heading||cfg.secondary)+'</h2><p>'+esc(d.demoClass?.text||"Choose a program and preferred slot; the team can confirm the next step.")+'</p></div><form id="edDemoForm" class="ed-form compact"><label>Name<input name="name" required placeholder="Student / parent name"></label><label>Phone<input name="phone" required type="tel" placeholder="+91"></label><label>Program / Class<select name="course" id="edDemoCourse">'+courses.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label>Preferred slot<select name="preferredBatch"><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Weekend</option></select></label><button class="ed-btn solid" type="submit">'+esc(d.demoClass?.buttonText||"Submit Enquiry")+' <span>↗</span></button><p id="edDemoNotice"></p></form></section>';
 if(visible("admission")) html+='<section id="admission" class="ed-section ed-admission"><div class="ed-admission-copy"><span class="ed-kicker">'+esc(cfg.leadLabel.toUpperCase())+'</span><h2>'+esc(d.admission?.heading||(typ==="School"?"Plan your school admission conversation.":"Talk to an academic counsellor."))+'</h2><p>'+esc(typ==="School"?d.school?.admissionText:d.admission?.text||"Share the learner’s program, class level and preferred timing.")+'</p><div class="ed-contact-links">'+(c.phone?'<a href="tel:'+safe(c.phone)+'"><span>Call</span>'+esc(c.phone)+'</a>':'')+(visible("whatsapp")&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'"><span>WhatsApp</span>Chat with admissions</a>':'')+'</div></div><form id="edAdmissionForm" class="ed-form"><div class="ed-form-grid"><label>Name<input name="name" required placeholder="Student / parent name"></label><label>Phone<input name="phone" required type="tel" placeholder="+91"></label><label>Email<input name="email" type="email" placeholder="you@example.com"></label><label>Program / Course<select name="course" id="edAdmissionCourse">'+courses.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label>Class / Level<input name="classLevel" placeholder="'+(typ==="College"?"Degree / Year":"Class / Level")+'"></label><label>Preferred Batch / Intake<select name="preferredBatch"><option>Morning</option><option>Afternoon</option><option>Evening</option><option>Weekend</option><option>Flexible</option></select></label><label>Mode<select name="mode"><option>Classroom</option><option>Online</option><option>Hybrid</option></select></label><label>Budget / Fee Range<select name="budget"><option>Under ₹10,000</option><option>₹10,000 – ₹25,000</option><option>₹25,000 – ₹50,000</option><option>₹50,000+</option><option>Discuss</option></select></label><label>Location<input name="location" placeholder="Area / City"></label></div><label>Message<textarea name="message" placeholder="Target course, class, department, learning goal or other details"></textarea></label><button class="ed-btn solid" type="submit">'+esc(d.admission?.buttonText||"Request Information")+' <span>↗</span></button><p id="edAdmissionNotice"></p></form></section>';
 if(visible("departments")) html+='<section id="departments" class="ed-section ed-departments"><div class="ed-head split"><div><span class="ed-kicker">DEPARTMENTS / SUBJECT AREAS</span><h2>Explore the academic areas behind the institution.</h2></div><p>'+esc(typ==="College"?d.college?.departmentsText||"Add department information.":"For schools and institutes, use this area for subjects, grade groups, labs or academic teams.")+'</p></div><div class="ed-department-grid">'+departments.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Department")+'"><div><span>'+esc(x.programs||"")+'</span><h3>'+esc(x.name||"Department")+'</h3><strong>'+esc(x.head||"")+'</strong><p>'+esc(x.text||"")+'</p></div></article>').join('')+'</div></section>';
 if(visible("results")) html+='<section class="ed-section ed-results"><div class="ed-head"><span class="ed-kicker">RESULTS & ACHIEVEMENTS</span><h2>Use verified numbers, academic milestones and achievements.</h2></div><div class="ed-result-grid">'+results.map(x=>'<article><strong>'+esc(x.value||"")+'</strong><h3>'+esc(x.title||"Achievement")+'</h3><p>'+esc(x.caption||"")+'</p></article>').join('')+'</div></section>';
 if(visible("placements")) html+='<section class="ed-section ed-placements"><div class="ed-head"><span class="ed-kicker">PLACEMENTS & CAREER OUTCOMES</span><h2>'+esc(d.college?.placementText||"Show career support, internships, placements and verified outcomes.")+'</h2></div><div class="ed-result-grid">'+placements.map(x=>'<article><strong>'+esc(x.value||"")+'</strong><h3>'+esc(x.title||"Career support")+'</h3><p>'+esc(x.caption||"")+'</p></article>').join('')+'</div></section>';
 if(visible("studentStories")) html+='<section class="ed-section"><div class="ed-head"><span class="ed-kicker">STUDENT / ALUMNI STORIES</span><h2>Real learning experiences from students and families.</h2></div><div class="ed-story-grid">'+stories.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.name||"Student")+'"><div><span>'+esc(x.course||"Program")+'</span><p>“'+esc(x.quote||"")+'”</p><strong>'+esc(x.name||"Student")+'</strong></div></article>').join('')+'</div></section>';
 if(visible("resources")) html+='<section class="ed-section ed-resources"><div class="ed-head split"><div><span class="ed-kicker">STUDY RESOURCES</span><h2>Give learners a useful next step.</h2></div><p>Link worksheets, syllabi, mock tests, prospectuses, brochures, orientation videos or student resources.</p></div><div class="ed-resource-grid">'+resources.map(x=>'<a target="_blank" href="'+esc(x.url||"#")+'"><span>'+esc(x.type||"Resource")+'</span><strong>'+esc(x.title||"Resource")+'</strong><p>'+esc(x.description||"")+'</p><b>Open ↗</b></a>').join('')+'</div></section>';
 if(visible("facilities")) html+='<section class="ed-section ed-facilities"><div class="ed-head"><span class="ed-kicker">CAMPUS & FACILITIES</span><h2>Show the environment supporting learning.</h2></div><div class="ed-facility-grid">'+facilities.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.title||"Facility")+'"><div><h3>'+esc(x.title||"Facility")+'</h3><p>'+esc(x.text||"")+'</p></div></article>').join('')+'</div></section>';
 if(visible("campusLife")) html+='<section class="ed-section ed-campus-life"><div class="ed-head"><span class="ed-kicker">CAMPUS LIFE</span><h2>'+esc(d.college?.campusLifeText||"Clubs, sports, events and activities beyond the classroom.")+'</h2></div><div class="ed-facility-grid">'+campusLife.map(x=>'<article><img src="'+esc(x.image||"")+'" alt="'+esc(x.title||"Campus life")+'"><div><h3>'+esc(x.title||"Activity")+'</h3><p>'+esc(x.text||"")+'</p></div></article>').join('')+'</div></section>';
 if(visible("notices")) html+='<section class="ed-section ed-notices"><div class="ed-head"><span class="ed-kicker">ANNOUNCEMENTS</span><h2>Keep students and families informed.</h2></div><div class="ed-notice-grid">'+notices.map(x=>'<article><span>'+esc(x.tag||"Notice")+'</span><small>'+esc(x.date||"")+'</small><h3>'+esc(x.title||"Notice")+'</h3><p>'+esc(x.text||"")+'</p></article>').join('')+'</div></section>';
 if(visible("calendar")) html+='<section class="ed-section ed-calendar"><div class="ed-head"><span class="ed-kicker">ACADEMIC CALENDAR</span><h2>Important dates in one clear timeline.</h2></div><div class="ed-calendar-list">'+calendar.map(x=>'<div><time>'+esc(x.date||"")+'</time><section><strong>'+esc(x.title||"Academic date")+'</strong><p>'+esc(x.text||"")+'</p></section></div>').join('')+'</div></section>';
 if(visible("transport")) html+='<section class="ed-section ed-transport"><div class="ed-head split"><div><span class="ed-kicker">TRANSPORT</span><h2>Bus routes and pickup information.</h2></div><p>'+esc(d.school?.transportText||"Add current route coverage, fees, timings and safety information.")+'</p></div><div class="ed-route-grid">'+transport.map(x=>'<article><span>'+esc(x.route||"Route")+'</span><strong>'+esc(x.time||"")+'</strong><h3>'+esc(x.areas||"Stops")+'</h3><p>'+esc(x.text||"")+'</p></article>').join('')+'</div></section>';
 if(visible("reviews")) html+='<section class="ed-section ed-reviews"><div class="ed-head"><span class="ed-kicker">STUDENT & PARENT REVIEWS</span><h2>What families and learners say about the experience.</h2></div><div class="ed-review-grid">'+reviews.map(x=>'<article>'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name||"Reviewer")+'">':'')+'<div class="ed-stars">'+('★'.repeat(Math.max(1,Math.min(5,num(x.rating)||5))))+'</div><p>“'+esc(x.text||"")+'”</p><strong>'+esc(x.name||"Reviewer")+'</strong><small>'+esc(x.type||"Student")+'</small></article>').join('')+'</div></section>';
 if(visible("about")) html+='<section class="ed-section ed-about"><div class="ed-head split"><div><span class="ed-kicker">ABOUT THE INSTITUTION</span><h2>'+esc(b.about||"Tell the institution story here.")+'</h2></div><p>'+esc(typ==="School"?((d.school?.curriculum||"")+" · "+(d.school?.grades||"")+" · "+(d.school?.academicYear||"")):typ==="College"?(d.college?.accreditation||"Add your verified affiliation and accreditation details."):"Explain your teaching approach, learning philosophy and learner support.")+'</p></div><div class="ed-about-stats"><div><strong>'+esc(b.foundedYear||"")+'</strong><span>founded</span></div><div><strong>'+esc(b.students||0)+'+</strong><span>learners / students</span></div><div><strong>'+esc(typ)+'</strong><span>education type</span></div></div></section>';
 if(visible("faq")) html+='<section class="ed-section"><div class="ed-head"><span class="ed-kicker">FAQ</span><h2>Before you enrol or visit.</h2></div><div class="ed-faq">'+faq.map(x=>'<details><summary>'+esc(x.question||"Question")+'<span>+</span></summary><p>'+esc(x.answer||"")+'</p></details>').join('')+'</div></section>';
 if(visible("location")||visible("hours")) html+='<section class="ed-section ed-location"><div><span class="ed-kicker">VISIT / CONTACT</span><h2>'+esc(b.businessName||"Your Institute")+'</h2><p>'+esc(c.address||"Add address here.")+'</p><p>'+esc(c.hoursText||"")+'</p><div class="ed-actions">'+(c.phone?'<a class="ed-btn solid" href="tel:'+safe(c.phone)+'">Call</a>':'')+(visible("whatsapp")&&c.whatsapp?'<a class="ed-btn outline" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+'</div></div>'+(c.maps?'<a class="ed-map" target="_blank" href="'+esc(c.maps)+'"><span>OPEN MAP</span><strong>Get directions ↗</strong><small>'+esc(c.address||"Institute location")+'</small></a>':'')+'</section>';
 if(visible("hours")) html+='<section class="ed-section ed-hours"><div class="ed-head"><span class="ed-kicker">OFFICE HOURS</span><h2>Talk to the team during office and counselling hours.</h2></div><div class="ed-hours-list"><div><strong>Weekdays</strong><span>'+esc(d.hours?.weekdays||"")+'</span></div><div><strong>Weekends</strong><span>'+esc(d.hours?.weekends||"")+'</span></div></div></section>';
 if(visible("terms")||visible("privacy")) html+='<section class="ed-legal">'+(visible("terms")?'<details open><summary>Terms & Policies</summary><p>'+esc(d.termsText||"")+'</p></details>':'')+(visible("privacy")?'<details><summary>Privacy Policy</summary><p>'+esc(d.privacyPolicy||"")+'</p></details>':'')+'</section>';
 html+='<footer class="ed-footer"><div><strong>'+esc(b.businessName||"Your Institute")+'</strong><span>'+esc(typeLabel(typ))+' · '+esc(b.tagline||"")+'</span></div><div>'+(c.phone?'<a href="tel:'+safe(c.phone)+'">Call</a>':'')+(visible("whatsapp")&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">Email</a>':'')+'</div></footer>';
 if(visible("whatsapp")&&c.whatsapp) html+='<a class="ed-float-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp ↗</a>';
 return html+'</div>';
}
export function init(root,d={}){
 const setSelect=(selector,value)=>{const e=root.querySelector(selector);if(e&&value)e.value=value};
 root.querySelectorAll('[data-course-select]').forEach(b=>b.onclick=()=>{setSelect('#edAdmissionCourse',b.dataset.courseSelect);root.querySelector('#admission')?.scrollIntoView({behavior:"smooth"})});
 root.querySelectorAll('[data-fee-plan]').forEach(b=>b.onclick=()=>{root.querySelector('#admission')?.scrollIntoView({behavior:"smooth"});setTimeout(()=>{const e=root.querySelector('#edAdmissionForm textarea[name="message"]');if(e)e.value='Interested in: '+(b.dataset.feePlan||'')},50)});
 root.querySelectorAll('[data-batch]').forEach(b=>b.onclick=()=>{setSelect('#edDemoCourse',b.dataset.batch);setSelect('#edAdmissionCourse',b.dataset.batch);root.querySelector('#demo')?.scrollIntoView({behavior:"smooth"})});
 root.querySelectorAll('.ed-filter').forEach(b=>b.onclick=()=>{root.querySelectorAll('.ed-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const cat=b.dataset.courseCat;root.querySelectorAll('[data-course-item]').forEach(x=>x.hidden=cat!=='all'&&x.dataset.courseItem!==cat)});
 const saveLead=(lead,noticeSelector,form)=>{
  lead.status="New";lead.createdAt=new Date().toISOString();lead.templateType=d.education?.type||"School";
  try{const state=Store.read(),data=structuredClone(state.data||d||{});data.leads=Array.isArray(data.leads)?data.leads:[];data.leads.unshift(lead);Store.update({data});const n=root.querySelector(noticeSelector);if(n)n.textContent="Request saved. The team can confirm the next step with you.";form.reset()}catch{const n=root.querySelector(noticeSelector);if(n)n.textContent="Could not save this request in the browser."}
  const wa=d.contact?.whatsapp;if(wa){const msg=['Education enquiry',lead.templateType,lead.leadType,lead.name,lead.phone,lead.email,lead.course,lead.classLevel,lead.preferredBatch,lead.mode,lead.budget,lead.location,lead.message].filter(Boolean).join("\\n");window.open('https://wa.me/'+safe(wa)+'?text='+encodeURIComponent(msg),'_blank')}
 };
 const df=root.querySelector('#edDemoForm');if(df)df.addEventListener('submit',e=>{e.preventDefault();const lead=Object.fromEntries(new FormData(df).entries());lead.leadType=d.education?.type==="School"?"Campus Visit / Demo":"Free Demo";saveLead(lead,'#edDemoNotice',df)});
 const af=root.querySelector('#edAdmissionForm');if(af)af.addEventListener('submit',e=>{e.preventDefault();const lead=Object.fromEntries(new FormData(af).entries());lead.leadType="Admission";saveLead(lead,'#edAdmissionNotice',af)});
}