(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=(o,p)=>p.split('.').reduce((x,k)=>x?.[k],o);
const set=(o,p,v)=>{const a=p.split('.');let x=o;a.slice(0,-1).forEach(k=>{if(!x[k]||typeof x[k]!=='object')x[k]={};x=x[k]});x[a.at(-1)]=v};
const root=p=>new URL(p,location.href).href;
const id=new URLSearchParams(location.search).get('template')||Store.read().templateId||'restaurant-01';
const t=getTemplate(id);if(!t){location.href='index.html';return}
let m,d,key='sitecraft:'+id,pickerTarget=null;
async function boot(){m=await fetch(root(t.manifest)).then(r=>{if(!r.ok)throw Error('Manifest load failed');return r.json()});d=load();$('#adminTemplateName').textContent=m.name||t.name;$('#adminTemplateCategory').textContent=m.category||t.category||'';build();bind();render()}
function load(){try{return JSON.parse(localStorage.getItem(key)||'null')||structuredClone(m.demoData||{})}catch{return structuredClone(m.demoData||{})}}
function save(msg='Saved'){try{localStorage.setItem(key,JSON.stringify(d));Store.update({templateId:id,data:structuredClone(d)});$('#saveIndicator').textContent=msg;toast(msg);renderStats()}catch{toast('Storage full')}}
function toast(x){const e=$('#toast');if(!e)return;e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function build(){const secs=m.admin?.sections||[];$('#sideNav').innerHTML=secs.map((s,i)=>`<button class="side-tab ${i?'':'active'}" data-tab="${esc(s.id)}">${esc(s.label)}</button>`).join('')+`<a class="side-tab side-link" href="index.html">View website ↗</a>`;$('#tabPanels').innerHTML=secs.map((s,i)=>`<section class="tab-panel ${i?'':'active'}" id="tab-${esc(s.id)}">${section(s)}</section>`).join('');$$('.side-tab[data-tab]').forEach(b=>b.onclick=()=>{$$('.side-tab[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-panel').forEach(x=>x.classList.remove('active'));$('#tab-'+b.dataset.tab).classList.add('active')})}
function mediaControl(label,value,target,compact=false){return`<div class="media-field ${compact?'compact':''}"><div><span class="media-label">${esc(label)}</span><small>${esc(value||'No image selected')}</small></div><button class="button ghost small" type="button" data-pick='${esc(JSON.stringify(target))}'>Choose image</button></div>`}
function field(f){const v=get(d,f.path);if(f.type==='checkbox')return`<label class="check-line"><input type="checkbox" data-path="${esc(f.path)}" ${v!==false?'checked':''}> ${esc(f.label)}</label>`;if(f.type==='media')return mediaControl(f.label,v,{kind:'path',path:f.path});if(f.type==='textarea')return`<label class="field wide"><span>${esc(f.label)}</span><textarea rows="5" data-path="${esc(f.path)}">${esc(v||'')}</textarea></label>`;if(f.type==='select')return`<label class="field"><span>${esc(f.label)}</span><select data-path="${esc(f.path)}">${(f.options||[]).map(o=>{const val=o.value??o;return`<option value="${esc(val)}" ${String(val)===String(v??'')?'selected':''}>${esc(o.label??o)}</option>`}).join('')}</select></label>`;return`<label class="field"><span>${esc(f.label)}</span><input data-path="${esc(f.path)}" type="${esc(f.type||'text')}" value="${esc(v||'')}" placeholder="${esc(f.placeholder||'')}"></label>`}
function section(s){
 if(s.type==='overview')return`<div class="page-head"><div><span class="kicker">SITECRAFT ADMIN</span><h1>Manage ${esc(m.name)}.</h1><p>Change your website after download from this control panel.</p></div></div><div class="stat-grid"><article><span>Images</span><strong id="statImages">0</strong></article><article><span>Menu / Services</span><strong id="statServices">0</strong></article><article><span>Gallery</span><strong id="statGallery">0</strong></article><article><span>Enquiries</span><strong id="statEnquiries">0</strong></article></div><div class="card overview-card"><h2 id="overviewName"></h2><p id="overviewMotto"></p></div>`;
 if(s.type==='collection')return`<div class="page-head"><div><span class="kicker">${esc(s.label)}</span><h1>${esc(s.title||s.label)}</h1><p>${esc(s.description||'Add, edit, reorder or remove items.')}</p></div></div><div class="card media-toolbar"><button class="button dark" data-add="${esc(s.id)}">+ Add ${esc(s.itemLabel||s.label)}</button></div><div id="list-${esc(s.id)}" class="repeat-list"></div>`;
 if(s.type==='media')return`<div class="page-head"><div><span class="kicker">IMAGES</span><h1>Upload once, reuse everywhere.</h1></div></div><div class="card media-toolbar"><label class="button dark file-btn">+ Upload images<input id="imageUpload" type="file" accept="image/*" multiple></label><span id="mediaCount"></span></div><div id="mediaGrid" class="media-grid"></div>`;
 if(s.type==='security')return`<div class="page-head"><div><span class="kicker">SECURITY</span><h1>Optional admin protection.</h1></div></div><div class="card form-card"><label class="check-line"><input id="passwordProtected" type="checkbox"> Password protection</label><div id="passwordBox"><div class="two-col"><label class="field"><span>Password</span><input id="newPassword" type="password"></label><label class="field"><span>Confirm</span><input id="confirmPassword" type="password"></label></div><button class="button dark" id="savePassword">Save password</button></div></div>`;
 return`<div class="page-head"><div><span class="kicker">${esc(s.label)}</span><h1>${esc(s.title||s.label)}</h1><p>${esc(s.description||'')}</p></div></div><div class="card form-card"><div class="two-col">${(s.fields||[]).map(field).join('')}</div></div>`}
function collectionField(s,it,i,f){
 const v=it[f.key];
 if(f.type==='checkbox')return`<label class="check-line"><input type="checkbox" data-item="${esc(s.id)}" data-id="${esc(it.id)}" data-key="${esc(f.key)}" ${v!==false?'checked':''}> ${esc(f.label)}</label>`;
 if(f.type==='media')return mediaControl(f.label,v,{kind:'item',sectionId:s.id,itemId:it.id,key:f.key},true);
 if(f.type==='textarea')return`<label class="field wide"><span>${esc(f.label)}</span><textarea data-item="${esc(s.id)}" data-id="${esc(it.id)}" data-key="${esc(f.key)}">${esc(v||'')}</textarea></label>`;
 if(f.type==='select')return`<label class="field"><span>${esc(f.label)}</span><select data-item="${esc(s.id)}" data-id="${esc(it.id)}" data-key="${esc(f.key)}">${(f.options||[]).map(o=>{const val=o.value??o;return`<option value="${esc(val)}" ${String(val)===String(v??'')?'selected':''}>${esc(o.label??o)}</option>`}).join('')}</select></label>`;
 return`<label class="field"><span>${esc(f.label)}</span><input data-item="${esc(s.id)}" data-id="${esc(it.id)}" data-key="${esc(f.key)}" value="${esc(v||'')}"></label>`}
function renderCollection(s){const r=$('#list-'+s.id);if(!r)return;const list=get(d,s.path)||[];r.innerHTML=list.map((it,i)=>`<article class="repeat-card"><div class="repeat-head"><div><span>${esc(s.itemLabel||s.label)} ${i+1}</span><strong>${esc(it[s.titleKey||'name']||it.title||'Untitled')}</strong></div><button class="button danger small" data-del="${esc(s.id)}" data-id="${esc(it.id)}">Delete</button></div><div class="two-col">${(s.fields||[]).map(f=>collectionField(s,it,i,f)).join('')}</div></article>`).join('')||'<div class="empty-state">No items yet. Use Add to create one.</div>'}
function renderMedia(){const r=$('#mediaGrid');if(!r)return;const a=(d.mediaLibrary||[]).filter(x=>x.type==='image');$('#mediaCount').textContent=a.length+' stored images';r.innerHTML=a.map(x=>`<article class="media-card"><div class="media-thumb"><img src="${esc(x.src)}" alt=""></div><div class="media-body"><strong>${esc(x.name)}</strong><div class="media-actions"><button class="button danger small" data-media-del="${esc(x.id)}">Delete</button></div></div></article>`).join('')||'<div class="empty-state">No images yet. Upload images to build your library.</div>'}
function renderStats(){const c=(id)=>{const s=m.admin?.sections?.find(x=>x.id===id);const a=s?get(d,s.path):[];return Array.isArray(a)?a.filter(x=>x.enabled!==false).length:0};if($('#statImages'))$('#statImages').textContent=(d.mediaLibrary||[]).length;if($('#statServices'))$('#statServices').textContent=c(m.id==='restaurant-01'?'menu':'services');if($('#statGallery'))$('#statGallery').textContent=c('gallery');if($('#statEnquiries'))$('#statEnquiries').textContent='0';if($('#overviewName'))$('#overviewName').textContent=get(d,m.admin?.overviewNamePath||'brand.businessName')||m.name;if($('#overviewMotto'))$('#overviewMotto').textContent=get(d,m.admin?.overviewMottoPath||'brand.tagline')||get(d,m.admin?.overviewMottoPath||'brand.motto')||''}
function render(){ $$('[data-path]').forEach(e=>{const v=get(d,e.dataset.path);if(e.type==='checkbox')e.checked=v!==false;else e.value=v??''});$$('.media-field').forEach(x=>{const b=x.querySelector('[data-pick]');if(!b)return;const target=JSON.parse(b.dataset.pick);const v=target.kind==='path'?get(d,target.path):((get(d,m.admin.sections.find(s=>s.id===target.sectionId)?.path)||[]).find(i=>i.id===target.itemId)?.[target.key]||'');const small=x.querySelector('small');if(small)small.textContent=v?'Image selected':'No image selected'});(m.admin?.sections||[]).filter(s=>s.type==='collection').forEach(renderCollection);renderMedia();renderStats();updateSecurity()}
function openPicker(target){pickerTarget=target;const a=(d.mediaLibrary||[]).filter(x=>x.type==='image');const o=$('#pickerOverlay'),g=$('#pickerGrid');if(!o||!g)return;g.innerHTML=a.map(x=>`<button class="picker-item" type="button" data-pick-id="${esc(x.id)}"><img src="${esc(x.src)}" alt=""><span>${esc(x.name)}</span></button>`).join('')||'<div class="empty-state">Upload an image first.</div>';o.hidden=false}
function closePicker(){$('#pickerOverlay').hidden=true;pickerTarget=null}
function bind(){
 document.addEventListener('input',e=>{if(e.target.matches('[data-path]')){set(d,e.target.dataset.path,e.target.type==='checkbox'?e.target.checked:e.target.value);save('Draft saved')}}); 
 document.addEventListener('change',e=>{if(e.target.matches('[data-path]')){set(d,e.target.dataset.path,e.target.type==='checkbox'?e.target.checked:e.target.value);save('Setting saved')}});
 document.addEventListener('input',e=>{if(e.target.matches('[data-item]')){const s=m.admin.sections.find(x=>x.id===e.target.dataset.item),it=(get(d,s.path)||[]).find(x=>x.id===e.target.dataset.id);if(it){it[e.target.dataset.key]=e.target.type==='checkbox'?e.target.checked:e.target.value;save('Item saved')}}});
 document.addEventListener('change',e=>{if(e.target.matches('[data-item]')){const s=m.admin.sections.find(x=>x.id===e.target.dataset.item),it=(get(d,s.path)||[]).find(x=>x.id===e.target.dataset.id);if(it){it[e.target.dataset.key]=e.target.type==='checkbox'?e.target.checked:e.target.value;save('Item saved')}}});
 document.addEventListener('click',e=>{
  const p=e.target.closest('[data-pick]');if(p){openPicker(JSON.parse(p.dataset.pick));return}
  const pi=e.target.closest('[data-pick-id]');if(pi&&pickerTarget){const img=(d.mediaLibrary||[]).find(x=>x.id===pi.dataset.pickId);if(img){if(pickerTarget.kind==='path')set(d,pickerTarget.path,img.src);else{const s=m.admin.sections.find(x=>x.id===pickerTarget.sectionId),it=(get(d,s.path)||[]).find(x=>x.id===pickerTarget.itemId);if(it)it[pickerTarget.key]=img.src}save('Image selected');render()}closePicker();return}
  const a=e.target.closest('[data-add]');if(a){const s=m.admin.sections.find(x=>x.id===a.dataset.add),list=get(d,s.path)||[],it={id:crypto.randomUUID(),...(s.addDefaults||{})};(s.fields||[]).forEach(f=>{if(it[f.key]===undefined)it[f.key]=f.default??(f.type==='checkbox'?true:'')});list.push(it);set(d,s.path,list);save('Item added');renderCollection(s);return}
  const del=e.target.closest('[data-del]');if(del){const s=m.admin.sections.find(x=>x.id===del.dataset.del);set(d,s.path,(get(d,s.path)||[]).filter(x=>x.id!==del.dataset.id));save('Item deleted');renderCollection(s);return}
  const md=e.target.closest('[data-media-del]');if(md&&confirm('Delete image?')){const removed=(d.mediaLibrary||[]).find(x=>x.id===md.dataset.mediaDel);d.mediaLibrary=(d.mediaLibrary||[]).filter(x=>x.id!==md.dataset.mediaDel);if(removed){(m.admin?.sections||[]).filter(s=>s.type==='collection').forEach(s=>{const list=get(d,s.path)||[];list.forEach(it=>(s.fields||[]).filter(f=>f.type==='media').forEach(f=>{if(it[f.key]===removed.src)it[f.key]=''}))});(m.admin?.sections||[]).forEach(s=>(s.fields||[]).filter(f=>f.type==='media').forEach(f=>{if(get(d,f.path)===removed.src)set(d,f.path,'')}))}save('Image deleted');render()}
 });
 $('#closePicker')?.addEventListener('click',closePicker);$('#pickerOverlay')?.addEventListener('click',e=>{if(e.target.id==='pickerOverlay')closePicker()});
 $('#saveTop').onclick=()=>save('All changes saved');
 $('#resetBtn').onclick=()=>{if(confirm('Reset this template?')){d=structuredClone(m.demoData||{});save('Defaults restored');location.reload()}};
 $('#exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download=id+'-settings.json';a.click()};
 $('#imageUpload')?.addEventListener('change',async e=>{for(const f of [...e.target.files]){try{const b=await createImageBitmap(f),c=document.createElement('canvas'),scale=Math.min(1,1800/Math.max(b.width,b.height));c.width=Math.max(1,Math.round(b.width*scale));c.height=Math.max(1,Math.round(b.height*scale));c.getContext('2d').drawImage(b,0,0,c.width,c.height);d.mediaLibrary=d.mediaLibrary||[];d.mediaLibrary.push({id:crypto.randomUUID(),name:f.name,type:'image',src:c.toDataURL('image/jpeg',.82)})}catch{toast('Could not process '+f.name)}}save('Images uploaded');render()});
}
function updateSecurity(){const p=$('#passwordProtected');if(!p)return;p.checked=d.settings?.passwordProtected===true;$('#passwordBox').hidden=!p.checked;p.onchange=()=>{d.settings=d.settings||{};d.settings.passwordProtected=p.checked;save('Security updated');updateSecurity()};$('#savePassword').onclick=()=>{const a=$('#newPassword').value,b=$('#confirmPassword').value;if(!a||a!==b)return toast('Passwords do not match');d.settings.adminPassword=a;d.settings.passwordProtected=true;save('Password saved');updateSecurity()}}
boot().catch(e=>{$('#adminApp').innerHTML='<div class="admin-error">Admin failed to start: '+esc(e.message)+'</div>'});
})();