window.SITECRAFT_TEMPLATES=[
  {id:'restaurant-01',group:'Restaurants',groupOrder:1,variant:'Signature',name:'Restaurant — Signature',category:'Restaurants',price:'₹4,999',thumbnail:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1000&q=85',manifest:'templates/restaurant-01/template.json',module:'templates/restaurant-01/template.js',style:'templates/restaurant-01/style.css'},
  {id:'restaurant-02',group:'Restaurants',groupOrder:1,variant:'Color Pop',name:'Restaurant — Color Pop',category:'Restaurants',price:'₹4,999',thumbnail:'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1000&q=85',manifest:'templates/restaurant-02/template.json',module:'templates/restaurant-02/template.js',style:'templates/restaurant-02/style.css'},
  {id:'photography-01',group:'Photography',groupOrder:2,variant:'Editorial',name:'Photography — Editorial',category:'Photography',price:'₹4,999',thumbnail:'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80',manifest:'templates/photography-01/template.json',module:'templates/photography-01/template.js',style:'templates/photography-01/style.css'},
  {id:'photography-02',group:'Photography',groupOrder:2,variant:'Cinematic',name:'Photography — Cinematic',category:'Photography',price:'₹4,999',thumbnail:'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=900&q=80',manifest:'templates/photography-02/template.json',module:'templates/photography-02/template.js',style:'templates/photography-02/style.css'},
  {id:'catering-01',group:'Catering Services',groupOrder:3,variant:'Celebration',name:'Catering — Celebration',category:'Catering Services',price:'₹4,999',thumbnail:'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1000&q=85',manifest:'templates/catering-01/template.json',module:'templates/catering-01/template.js',style:'templates/catering-01/style.css'},
  {id:'realestate-01',group:'Real Estate',groupOrder:4,variant:'Property Showcase',name:'Real Estate — Property Showcase',category:'Real Estate Agencies & Brokers',price:'₹4,999',thumbnail:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85',manifest:'templates/realestate-01/template.json',module:'templates/realestate-01/template.js',style:'templates/realestate-01/style.css'},
  {id:'realestate-02',group:'Real Estate',groupOrder:4,variant:'Luxury Corporate',name:'Real Estate — Luxury Corporate',category:'Real Estate Agencies & Brokers',price:'₹4,999',thumbnail:'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=85',manifest:'templates/realestate-02/template.json',module:'templates/realestate-02/template.js',style:'templates/realestate-02/style.css'}
];
window.getTemplate=id=>window.SITECRAFT_TEMPLATES.find(t=>t.id===id);