const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
const priceValue=p=>{const n=Number(p);return Number.isFinite(n)?n:parseFloat(String(p??'').replace(/[^0-9.]/g,''))||0};
const fmtBudget=n=>{const v=Number(n)||0;return v>=100?'₹'+(v/100).toFixed(v%100?1:0)+' Cr':'₹'+v+' L'};
const moneyLakhs=v=>{const n=Number(v)||0;if(!n)return '';return n>=10000000?'₹'+(n/10000000).toFixed(2).replace(/\.00$/,'')+' Cr':'₹'+(n/100000).toFixed(0)+' L';};

export function render(d={},selected=[]){
  const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},e=d.enquiry||{},ok=x=>selected.includes(x);
  const props=(d.properties||[]).filter(x=>x.enabled!==false),services=(d.services||[]).filter(x=>x.enabled!==false),agents=(d.agents||[]).filter(x=>x.enabled!==false),reviews=(d.reviews||[]).filter(x=>x.enabled!==false),faq=(d.faq||[]).filter(x=>x.enabled!==false),landmarks=(d.landmarks||[]).filter(x=>x.enabled!==false);
  const featured=props.filter(x=>x.featured||x.status==='Featured'),featuredList=featured.length?featured:props.slice(0,2);
  let html='<div class="site-preview realestate-02">';
  html+='<header class="lux-nav"><a class="lux-brand" href="#home"><span class="lux-monogram">AE</span><span><strong>'+esc(b.businessName||'Aurum Estates')+'</strong><small>'+esc(b.tagline||'PRIVATE PROPERTY ADVISORY')+'</small></span></a><nav>';
  if(ok('home'))html+='<a href="#home">Home</a>';if(ok('gallery'))html+='<a href="#properties">Collection</a>';if(ok('services'))html+='<a href="#services">Services</a>';if(ok('agents'))html+='<a href="#team">Advisors</a>';if(ok('reviews'))html+='<a href="#reviews">Reviews</a>';if(ok('faq'))html+='<a href="#faq">FAQ</a>';if(ok('enquiry'))html+='<a href="#enquiry">Contact</a>';
  html+='</nav><div class="lux-nav-actions">'+(ok('whatsapp')&&c.whatsapp?'<a class="lux-whatsapp" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+'<a class="template-admin-link" href="admin.html?template=realestate-02">Admin</a></div></header>';

  if(ok('home'))html+='<section id="home" class="lux-hero"><div class="lux-hero-image"><img src="'+esc(d.hero||'')+'" alt="'+esc(b.businessName||'Real estate')+'"></div><div class="lux-hero-overlay"></div><div class="lux-hero-copy"><span class="lux-eyebrow">PRIVATE PROPERTY COLLECTION · HYDERABAD</span><h1>'+esc(h.title||'Rare addresses.<br>Considered decisions.')+'</h1><p>'+esc(h.text||'Discover premium homes, land and commercial opportunities through a more deliberate buying experience.')+'</p><div class="lux-actions">'+(ok('enquiry')?'<a class="lux-btn gold" href="#enquiry">Arrange a private visit <span>↗</span></a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="lux-btn glass" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">Speak to an advisor <span>↗</span></a>':'')+'</div></div><div class="lux-hero-meta"><span>EST.</span><strong>2009</strong><span>CURATED</span><strong>'+props.length.toString().padStart(2,'0')+'</strong></div></section>';

  if(ok('home')&&featuredList.length)html+='<section class="lux-featured"><div class="lux-featured-head"><div><span class="lux-eyebrow">THE COLLECTION</span><h2>Featured addresses</h2></div><p>Selected homes and opportunities. Open a card for full details, photos and a direct enquiry.</p></div><div class="lux-featured-grid">'+featuredList.slice(0,3).map((x,i)=>'<article class="lux-featured-card" data-detail-id="'+esc(x.id)+'"><div class="lux-featured-image"><img src="'+esc(x.coverImage||'')+'" alt="'+esc(x.title||'')+'"><span>0'+(i+1)+'</span></div><div class="lux-featured-body"><small>'+esc(x.type||'PROPERTY')+' · '+esc(x.location||'')+'</small><h3>'+esc(x.title||'Property')+'</h3><strong>'+esc(x.price||moneyLakhs(x.priceValue)||'Price on request')+'</strong><button type="button" class="lux-line-btn" data-detail-id="'+esc(x.id)+'">View details <span>→</span></button></div></article>').join('')+'</div></section>';

  if(ok('home')&&props.length)html+='<section class="lux-search"><div class="lux-search-intro"><span class="lux-eyebrow">PRIVATE SEARCH</span><h2>Find the right fit.</h2><p>Filter the collection by location, property type, BHK and budget.</p></div><form id="luxPropertySearch" class="lux-search-form"><label><span>Location</span><input name="location" placeholder="Jubilee Hills"></label><label><span>Property type</span><select name="type"><option value="">Any type</option><option>Apartment</option><option>Villa</option><option>Open Plot</option><option>Commercial Space</option><option>Independent House</option><option>Farm Land</option></select></label><label><span>BHK</span><select name="bhk"><option value="">Any BHK</option><option>1 BHK</option><option>2 BHK</option><option>3 BHK</option><option>4 BHK</option><option>5 BHK</option></select></label><label class="lux-range"><span>Budget up to <b id="luxBudgetValue">₹5 Cr</b></span><input id="luxBudgetRange" name="budget" type="range" min="25" max="500" step="5" value="500"></label><button class="lux-btn dark" type="submit">Search collection <span>↗</span></button></form><div id="luxSearchNote" class="lux-search-note"></div></section>';

  if(ok('about')&&s.showAbout!==false)html+='<section id="about" class="lux-section lux-about"><div class="lux-side"><span class="lux-eyebrow">ABOUT THE FIRM</span><span>01 / 07</span></div><div class="lux-about-main"><h2>'+esc(b.businessName||'Aurum Estates')+' is built around the idea that property advice should feel personal, clear and considered.</h2><p>'+esc(b.about||'Tell your story in Admin > Business.')+'</p><div class="lux-about-sign"><strong>'+esc(b.ownerName||'Principal Advisor')+'</strong><span>Founder / Lead Advisor</span></div></div></section>';

  if(ok('gallery')&&s.showGallery!==false)html+='<section id="properties" class="lux-section lux-properties"><div class="lux-section-head"><div><span class="lux-eyebrow">PROPERTY LISTINGS</span><h2>The private collection</h2></div><p>Every listing is editable in Admin. Use View details to open a focused property profile with photos and enquiry action.</p></div><div id="luxPropertyGrid" class="lux-property-grid">'+props.map((x,i)=>'<article class="lux-property-card" data-property data-location="'+esc((x.location||'').toLowerCase())+'" data-type="'+esc(x.type||'')+'" data-bhk="'+esc(x.bhk||'')+'" data-price="'+priceValue(x.priceValue||x.price)+'"><div class="lux-card-image"><img src="'+esc(x.coverImage||'')+'" alt="'+esc(x.title||'')+'"><span class="lux-card-index">0'+(i+1)+'</span><span class="lux-status">'+esc(x.status||'Available')+'</span></div><div class="lux-card-body"><div class="lux-card-top"><small>'+esc(x.type||'Property')+' · '+esc(x.location||'')+'</small><strong>'+esc(x.price||moneyLakhs(x.priceValue)||'Price on request')+'</strong></div><h3>'+esc(x.title||'Property')+'</h3><div class="lux-specs"><span>'+esc(x.bhk||'—')+'</span><span>'+esc(x.area||'—')+'</span><span>'+esc(x.bathrooms||'—')+' baths</span></div><p>'+esc(x.description||'')+'</p><button type="button" class="lux-line-btn" data-detail-id="'+esc(x.id)+'">View property <span>↗</span></button></div></article>').join('')+'</div><div id="luxNoResults" class="lux-empty" hidden>No properties match those filters. Try a broader search or contact the advisory team.</div></section>';

  if(ok('services')&&s.showServices!==false)html+='<section id="services" class="lux-section lux-services"><div class="lux-section-head"><div><span class="lux-eyebrow">ADVISORY SERVICES</span><h2>Support beyond the search.</h2></div><p>Show clients how your agency supports the journey before, during and after the property decision.</p></div><div class="lux-service-list">'+services.map((x,i)=>'<article><span>0'+(i+1)+'</span><div><h3>'+esc(x.name||'Advisory service')+'</h3><p>'+esc(x.description||'')+'</p></div><b>↗</b></article>').join('')+'</div></section>';

  if(ok('agents')&&s.showAgents!==false)html+='<section id="team" class="lux-section lux-team"><div class="lux-section-head"><div><span class="lux-eyebrow">ADVISORS</span><h2>A quieter kind of expertise.</h2></div></div><div class="lux-agent-grid">'+agents.map(x=>'<article><div class="lux-agent-image">'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name||'')+'">':'')+'</div><div class="lux-agent-copy"><small>'+esc(x.role||'Property Advisor')+'</small><h3>'+esc(x.name||'Advisor')+'</h3><p>'+esc(x.bio||'')+'</p></div></article>').join('')+'</div></section>';

  if(ok('reviews')&&s.showReviews!==false)html+='<section id="reviews" class="lux-section lux-reviews"><div class="lux-review-number">02</div><div class="lux-review-content"><span class="lux-eyebrow">CLIENT NOTES</span><h2>Trust is built in the details.</h2><div class="lux-review-grid">'+reviews.map(x=>'<article><b class="lux-stars">'+'★'.repeat(Number(x.rating)||0)+'</b><p>“'+esc(x.text||'')+'”</p><strong>'+esc(x.name||'Client')+'</strong></article>').join('')+'</div></div></section>';

  if(ok('location')&&s.showLocation!==false)html+='<section id="location" class="lux-section lux-location"><div class="lux-section-head"><div><span class="lux-eyebrow">LOCATION & LANDMARKS</span><h2>Context matters.</h2></div><p>'+esc(c.address||'Add your office address in Admin > Contact.')+'</p></div><div class="lux-landmarks">'+landmarks.map((x,i)=>'<article><span>0'+(i+1)+'</span><h3>'+esc(x.name||'Landmark')+'</h3><p>'+esc(x.text||'')+'</p></article>').join('')+'</div><div class="lux-location-actions">'+(c.maps?'<a class="lux-btn dark" target="_blank" href="'+esc(c.maps)+'">Open office location <span>↗</span></a>':'')+(c.phone?'<a class="lux-line-btn" href="tel:'+esc(c.phone)+'">Call '+esc(c.phone)+' <span>↗</span></a>':'')+'</div></section>';

  if(ok('faq')&&s.showFAQ!==false)html+='<section id="faq" class="lux-section lux-faq"><div class="lux-side"><span class="lux-eyebrow">FAQ</span><span>06 / 07</span></div><div class="lux-faq-list">'+faq.map((x,i)=>'<article><button type="button" data-faq-toggle aria-expanded="false"><span>0'+(i+1)+' '+esc(x.question||'Question')+'</span><b>+</b></button><div data-faq-answer hidden><p>'+esc(x.answer||'')+'</p></div></article>').join('')+'</div></section>';

  if(ok('enquiry')&&s.showEnquiry!==false)html+='<section id="enquiry" class="lux-enquiry"><div class="lux-enquiry-copy"><span class="lux-eyebrow">PRIVATE APPOINTMENT</span><h2>'+esc(e.heading||'Let us arrange the next conversation.')+'</h2><p>'+esc(e.text||'Tell us the property type, budget and preferred timing. The advisory team can follow up with a focused shortlist or site visit.')+'</p><div class="lux-contact-stack">'+(c.phone?'<a href="tel:'+esc(c.phone)+'">'+esc(c.phone)+'</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':'')+'</div></div><form id="luxEnquiryForm" class="lux-enquiry-form"><label><span>Name</span><input name="name" required placeholder="Your name"></label><label><span>Phone</span><input name="phone" required placeholder="+91"></label><label><span>Email</span><input name="email" type="email" placeholder="you@example.com"></label><label><span>Property Type</span><select name="propertyType"><option value="">Choose</option><option>Apartment</option><option>Villa</option><option>Open Plot</option><option>Commercial Space</option><option>Independent House</option><option>Farm Land</option></select></label><label class="lux-budget-field"><span>Budget up to <b id="luxEnquiryBudgetValue">₹2 Cr</b></span><input id="luxEnquiryBudget" name="budgetValue" type="range" min="25" max="500" step="5" value="200"><small>₹25 Lakhs – ₹5 Crore</small></label><fieldset><legend>Purpose</legend><label><input type="checkbox" name="purpose" value="Buying"> Buying</label><label><input type="checkbox" name="purpose" value="Investing"> Investment</label></fieldset><label><span>Property of interest</span><input id="luxSelectedProperty" name="property" placeholder="Optional"></label><label><span>Preferred visit date</span><input name="visitDate" type="date"></label><label><span>Preferred time</span><input name="visitTime" type="time"></label><label class="lux-wide"><span>Message</span><textarea name="message" rows="4" placeholder="Share anything the advisor should know."></textarea></label><button class="lux-btn gold lux-wide" type="submit">Request private appointment <span>↗</span></button></form></section>';

  if(ok('terms')&&s.showTerms!==false)html+='<section class="lux-legal"><span class="lux-eyebrow">TERMS & CONDITIONS</span><p>'+esc(d.termsText||'')+'</p></section>';
  if(ok('privacy')&&s.showPrivacy!==false)html+='<section id="privacy" class="lux-legal light"><span class="lux-eyebrow">PRIVACY POLICY</span><p>'+esc(d.privacyPolicy||'')+'</p></section>';
  if(ok('rera')&&s.showRera!==false)html+='<section id="rera" class="lux-rera"><div><span class="lux-eyebrow">RERA INFORMATION</span><h2>Verify registration details before proceeding.</h2><p>'+esc(d.rera?.text||'')+'</p></div><strong>'+esc(d.rera?.number||'Add RERA / registration number in Admin')+'</strong></section>';

  html+='<div id="luxDetailModal" class="lux-modal" hidden><div class="lux-modal-backdrop" data-close-modal></div><div class="lux-modal-panel" role="dialog" aria-modal="true" aria-labelledby="luxModalTitle"><button type="button" class="lux-modal-close" data-close-modal aria-label="Close">×</button><div id="luxModalBody"></div></div></div>';
  html+='<footer class="lux-footer"><div><span class="lux-monogram">AE</span><div><strong>'+esc(b.businessName||'Aurum Estates')+'</strong><small>'+esc(b.tagline||'Private Property Advisory')+'</small></div></div><div class="lux-footer-links">'+(c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp ↗</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':'')+'</div><a class="template-admin-link" href="admin.html?template=realestate-02">Admin</a></footer></div>';
  return html;
}

export function init(root,d={},selected=[]){
  const c=d.contact||{},props=(d.properties||[]).filter(x=>x.enabled!==false);
  const fmt=n=>fmtBudget(n);
  const updateRange=(input,out)=>{if(input&&out)out.textContent=fmt(input.value)};
  const sr=root.querySelector('#luxBudgetRange'),sv=root.querySelector('#luxBudgetValue');updateRange(sr,sv);sr?.addEventListener('input',()=>updateRange(sr,sv));
  const eb=root.querySelector('#luxEnquiryBudget'),ev=root.querySelector('#luxEnquiryBudgetValue');updateRange(eb,ev);eb?.addEventListener('input',()=>updateRange(eb,ev));

  const modal=root.querySelector('#luxDetailModal'),body=root.querySelector('#luxModalBody');
  const openDetail=id=>{
    const x=props.find(p=>p.id===id);if(!x||!modal||!body)return;
    const photos=(x.photos||[]).filter(p=>p.enabled!==false&&p.image);
    body.innerHTML='<div class="lux-modal-grid"><div class="lux-modal-media"><img src="'+esc(x.coverImage||photos[0]?.image||'')+'" alt="'+esc(x.title||'')+'">'+(photos.length?'<div class="lux-photo-strip">'+photos.map(p=>'<button type="button" data-modal-photo="'+esc(p.image)+'"><img src="'+esc(p.image)+'" alt="'+esc(p.title||'Photo')+'"></button>').join('')+'</div>':'')+'</div><div class="lux-modal-copy"><span class="lux-eyebrow">'+esc(x.type||'PROPERTY')+' · '+esc(x.status||'AVAILABLE')+'</span><h2 id="luxModalTitle">'+esc(x.title||'Property')+'</h2><strong class="lux-modal-price">'+esc(x.price||moneyLakhs(x.priceValue)||'Price on request')+'</strong><p class="lux-modal-location">⌖ '+esc(x.location||'')+'</p><div class="lux-modal-specs"><span>'+esc(x.bhk||'—')+'</span><span>'+esc(x.area||'—')+'</span><span>'+esc(x.bathrooms||'—')+' baths</span></div><p>'+esc(x.description||'')+'</p><div class="lux-amenities">'+String(x.amenities||'').split('·').map(v=>v.trim()).filter(Boolean).map(v=>'<span>'+esc(v)+'</span>').join('')+'</div><div class="lux-modal-actions">'+(selected.includes('enquiry')?'<button type="button" class="lux-btn gold" data-modal-enquire="'+esc(x.title||'')+'">Enquire about this property <span>↗</span></button>':'')+(c.whatsapp?'<a class="lux-btn dark" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'?text='+encodeURIComponent('Hello '+(businessName(d)||'Team')+', I am interested in '+(x.title||'this property')+'.')+'">WhatsApp advisor <span>↗</span></a>':'')+'</div></div></div>';
    modal.hidden=false;document.body.style.overflow='hidden';
    body.querySelectorAll('[data-modal-photo]').forEach(btn=>btn.addEventListener('click',()=>{const img=body.querySelector('.lux-modal-media>img');if(img)img.src=btn.dataset.modalPhoto}));
    body.querySelector('[data-modal-enquire]')?.addEventListener('click',()=>{const f=root.querySelector('#luxSelectedProperty');if(f)f.value=x.title||'';modal.hidden=true;document.body.style.overflow='';root.querySelector('#enquiry')?.scrollIntoView({behavior:'smooth'})});
  };
  const businessName=data=>data?.brand?.businessName||'Aurum Estates';
  root.querySelectorAll('[data-detail-id]').forEach(btn=>btn.addEventListener('click',()=>openDetail(btn.dataset.detailId)));
  root.querySelectorAll('[data-close-modal]').forEach(btn=>btn.addEventListener('click',()=>{modal.hidden=true;document.body.style.overflow=''}));

  root.querySelector('#luxPropertySearch')?.addEventListener('submit',e=>{
    e.preventDefault();const f=new FormData(e.currentTarget),loc=String(f.get('location')||'').toLowerCase().trim(),type=String(f.get('type')||''),bhk=String(f.get('bhk')||''),budget=(Number(f.get('budget'))||500)*100000;let n=0;
    root.querySelectorAll('[data-property]').forEach(card=>{const okLoc=!loc||card.dataset.location.includes(loc),okType=!type||card.dataset.type===type,okBhk=!bhk||card.dataset.bhk===bhk,okBudget=!Number(card.dataset.price)||Number(card.dataset.price)<=budget;const show=okLoc&&okType&&okBhk&&okBudget;card.hidden=!show;if(show)n++});
    root.querySelector('#luxSearchNote').textContent=n+' matching '+(n===1?'property':'properties');root.querySelector('#luxNoResults').hidden=n!==0;
  });

  root.querySelectorAll('[data-faq-toggle]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.parentElement?.querySelector('[data-faq-answer]'),open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));if(a)a.hidden=open;btn.classList.toggle('open',!open)}));
  root.querySelector('#luxEnquiryForm')?.addEventListener('submit',e=>{
    e.preventDefault();const f=new FormData(e.currentTarget);
    if(!safe(c.whatsapp)){alert('Please add a WhatsApp number in Admin > Contact.');return}
    const purposes=[...e.currentTarget.querySelectorAll('input[name="purpose"]:checked')].map(x=>x.value).join(', ')||'Not specified';
    const lead={id:crypto.randomUUID(),createdAt:new Date().toLocaleString(),name:f.get('name')||'',phone:f.get('phone')||'',email:f.get('email')||'',property:f.get('property')||'',propertyType:f.get('propertyType')||'',budget:fmt(f.get('budgetValue')),purpose:purposes,visitDate:f.get('visitDate')||'',visitTime:f.get('visitTime')||'',message:f.get('message')||''};
    try{const key='sitecraft:realestate-02',saved=JSON.parse(localStorage.getItem(key)||'{}');saved.leads=Array.isArray(saved.leads)?saved.leads:[];saved.leads.unshift(lead);localStorage.setItem(key,JSON.stringify(saved))}catch{}
    const msg=['Hello '+businessName(d)+'!','','New property enquiry:','Name: '+lead.name,'Phone: '+lead.phone,'Email: '+(lead.email||'Not specified'),'Property: '+(lead.property||'Not specified'),'Property Type: '+(lead.propertyType||'Not specified'),'Budget: '+lead.budget,'Purpose: '+lead.purpose,'Site Visit Date: '+(lead.visitDate||'Not specified'),'Site Visit Time: '+(lead.visitTime||'Not specified'),'Message: '+(lead.message||'')].join('\n');
    window.open('https://wa.me/'+safe(c.whatsapp)+'?text='+encodeURIComponent(msg),'_blank');
  });
}
