const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
export function render(d={},selected=[]) {
  const b=d.brand||{}, h=d.home||{}, c=d.contact||{}, s=d.settings||{}, e=d.enquiry||{}, ok=x=>selected.includes(x);
  const menu=(d.menu||[]).filter(x=>x.enabled!==false), gallery=(d.gallery||[]).filter(x=>x.enabled!==false), reviews=(d.reviews||[]).filter(x=>x.enabled!==false);
  let html='<div class="site-preview catering-01">';
  html+='<header class="cat-nav"><a class="cat-brand" href="#home"><strong>'+esc(b.businessName||'Your Catering Business')+'</strong><small>'+esc(b.tagline||'CATERING & EVENTS')+'</small></a><nav>';
  if(ok('home')) html+='<a href="#home">Home</a>'; if(ok('about')) html+='<a href="#about">About</a>'; if(ok('menu')) html+='<a href="#menu">Menu</a>'; if(ok('gallery')) html+='<a href="#gallery">Gallery</a>'; if(ok('reviews')) html+='<a href="#reviews">Reviews</a>'; if(ok('enquiry')) html+='<a href="#enquiry">Enquiry</a>';
  html+='</nav><div class="cat-nav-actions">';
  if(ok('whatsapp')&&c.whatsapp) html+='<a class="cat-mini-btn accent" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>';
  html+='<a class="template-admin-link" href="admin.html?template=catering-01">Admin</a></div></header>';
  if(ok('home')) html+='<section id="home" class="cat-hero"><div class="cat-hero-photo"><img src="'+esc(d.hero||'')+'" alt="'+esc(b.businessName||'Catering')+'"></div><div class="cat-hero-copy"><span class="cat-kicker">EVENT CATERING · WEDDINGS · PARTIES · CORPORATE</span><h1>'+esc(h.title||b.businessName||'Catering made for memorable celebrations.')+'</h1><p>'+esc(h.text||'')+'</p><div class="cat-actions">'+(ok('enquiry')?'<a class="cat-btn dark" href="#enquiry">Plan your event <i>↗</i></a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="cat-btn outline" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">Chat on WhatsApp <i>↗</i></a>':'')+'</div><div class="cat-hero-note"><span>Weddings</span><span>Birthdays</span><span>Corporate</span><span>House parties</span></div></div></section>';
  if(ok('about')&&s.showAbout!==false) html+='<section id="about" class="cat-section cat-about"><div class="cat-section-label">OUR STORY</div><div><h2>Food, service and a calm event day.</h2><p>'+esc(b.about||'Tell your story from Admin > Business.')+'</p></div><div class="cat-about-stats"><div><strong>Fresh</strong><span>menu planning</span></div><div><strong>Flexible</strong><span>event formats</span></div><div><strong>Care</strong><span>on-site service</span></div></div></section>';
  if(ok('menu')&&s.showMenu!==false) { html+='<section id="menu" class="cat-section cat-menu"><div class="cat-heading"><div><span class="cat-kicker">MENU & PACKAGES</span><h2>Choose a format. Then make it yours.</h2></div><p>Add or edit every package from Admin. Guest count and plate price can stay blank whenever you quote custom.</p></div><div class="cat-menu-grid>';
    menu.forEach((x,i)=>{ html+='<article class="cat-package"><div class="cat-package-image"><img src="'+esc(x.image||'')+'" alt="'+esc(x.name||'')+'"><span>'+String(i+1).padStart(2,'0')+'</span></div><div class="cat-package-body"><small>'+esc(x.category||'CATERING PACKAGE')+'</small><h3>'+esc(x.name||'Untitled package')+'</h3><p>'+esc(x.description||'')+'</p><div class="cat-package-meta">'; if(x.serves) html+='<span><b>Serves</b>'+esc(x.serves)+'</span>'; if(x.pricePerPlate) html+='<span><b>Price</b>'+esc(x.pricePerPlate)+'</span>'; html+='</div>'; if(ok('enquiry')) html+='<a class="cat-text-link" href="#enquiry" data-package="'+esc(x.name||'')+'">Ask about this package ↗</a>'; html+='</div></article>'; });
    html+='</div></section>';
  }
  if(ok('gallery')&&s.showGallery!==false) { html+='<section id="gallery" class="cat-section cat-gallery"><div class="cat-heading"><div><span class="cat-kicker">GALLERY</span><h2>A taste of the celebrations.</h2></div><p>Use Admin to add, replace, or remove images as your portfolio grows.</p></div><div class="cat-gallery-grid>'; gallery.forEach((x,i)=>html+='<figure><img src="'+esc(x.image||'')+'" alt="'+esc(x.title||'')+'"><figcaption><b>0'+(i+1)+'</b><span>'+esc(x.title||'')+'</span></figcaption></figure>'); html+='</div></section>'; }
  if(ok('reviews')&&s.showReviews!==false) { html+='<section id="reviews" class="cat-section cat-reviews"><div class="cat-heading"><div><span class="cat-kicker">CUSTOMER REVIEWS</span><h2>Trusted by hosts and teams.</h2></div></div><div class="cat-review-grid>'; reviews.forEach(x=>html+='<article><b class="stars">'+'★'.repeat(Number(x.rating)||0)+'</b><p>“'+esc(x.text||'')+'”</p><strong>'+esc(x.name||'Customer')+'</strong></article>'); html+='</div></section>'; }
  if(ok('enquiry')&&s.showEnquiry!==false) html+='<section id="enquiry" class="cat-section cat-enquiry"><div class="cat-enquiry-copy"><span class="cat-kicker">ENQUIRY</span><h2>'+esc(e.heading||'Tell us about your celebration.')+'</h2><p>'+esc(e.text||'Share your date, guest count and event type.')+'</p><div class="cat-event-tags"><span>Weddings</span><span>Corporate</span><span>Birthdays</span><span>Private parties</span></div></div><form id="cateringEnquiryForm" class="cat-form"><label><span>Your name</span><input name="name" required placeholder="Your name"></label><label><span>Phone</span><input name="phone" required placeholder="+91"></label><label><span>Event date</span><input name="date" type="date" required></label><label><span>Guests (optional)</span><input name="guests" type="number" min="1" placeholder="50"></label><label class="wide"><span>Event type</span><input name="eventType" placeholder="Wedding / Birthday / Corporate"></label><label class="wide"><span>Message</span><textarea name="message" rows="4" placeholder="Venue, food preferences or anything important."></textarea></label><button class="cat-btn dark wide" type="submit">'+esc(e.buttonText||'Send enquiry on WhatsApp')+' <i>↗</i></button></form></section>';
  if((ok('location')||c.address) && (ok('location')||c.address)) html+='<section class="cat-location"><div><span class="cat-kicker">FIND US</span><h2>'+esc(b.businessName||'Your Catering Business')+'</h2><p>'+esc(c.address||'Add your address in Admin > Contact.')+'</p></div><div class="cat-actions">'+(ok('location')&&c.maps?'<a class="cat-btn light" target="_blank" href="'+esc(c.maps)+'">Open location ↗</a>':'')+(c.phone?'<a class="cat-btn outline-dark" href="tel:'+esc(c.phone)+'">Call</a>':'')+'</div></section>';
  if(ok('privacy')&&s.showPrivacy!==false) html+='<section id="privacy" class="cat-privacy"><span class="cat-kicker">PRIVACY POLICY</span><p>'+esc(d.privacyPolicy||'Your privacy policy will appear here.')+'</p></section>';
  html+='<footer class="cat-footer"><div><strong>'+esc(b.businessName||'Your Catering Business')+'</strong><span>'+esc(b.tagline||'Catering & Events')+'</span></div><div class="cat-footer-links">'+(c.maps?'<a target="_blank" href="'+esc(c.maps)+'">Location ↗</a>':'')+(c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp ↗</a>':'')+'</div><a class="template-admin-link" href="admin.html?template=catering-01">Admin</a></footer></div>';
  return html;
}
export function init(root,d={},selected=[]) {
  const c=d.contact||{};
  root.querySelectorAll('[data-package]').forEach(link=>link.addEventListener('click',()=>{const f=root.querySelector('#cateringEnquiryForm'); if(f){const p=f.querySelector('input[name="eventType"]'); if(p&&!p.value) p.value='Package enquiry: '+link.dataset.package;}}));
  root.querySelector('#cateringEnquiryForm')?.addEventListener('submit',e=>{
    e.preventDefault();
    if(!safe(c.whatsapp)){alert('Please add a WhatsApp number in Admin > Contact.');return}
    const f=new FormData(e.currentTarget);
    const text=['Hello '+(d.brand?.businessName||'Catering Team')+'!','','Catering enquiry:','Name: '+(f.get('name')||''),'Phone: '+(f.get('phone')||''),'Event date: '+(f.get('date')||''),'Guests: '+(f.get('guests')||'Not specified'),'Event type: '+(f.get('eventType')||'Not specified'),'Message: '+(f.get('message')||'')].join('\n');
    window.open('https://wa.me/'+safe(c.whatsapp)+'?text='+encodeURIComponent(text),'_blank');
  });
}