const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
const wa=(n,msg='')=>{const p=safe(n);return p?'https://wa.me/'+p+(msg?'?text='+encodeURIComponent(msg):''):''};
export function render(d={},selected=[]){
 const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},hours=d.hours||{},a=d.appointment||{},ok=x=>selected.includes(x);
 const services=(d.services||[]).filter(x=>x.enabled!==false),doctors=(d.doctors||[]).filter(x=>x.enabled!==false),fac=(d.facilities||[]).filter(x=>x.enabled!==false),gallery=(d.gallery||[]).filter(x=>x.enabled!==false&&x.image),reviews=(d.reviews||[]).filter(x=>x.enabled!==false),faq=(d.faq||[]).filter(x=>x.enabled!==false);
 let html='<div class="site-preview medical-01"><header class="medical-01-nav"><a class="medical-01-brand" href="#home"><span class="medical-01-mark">CP</span><span><strong>'+esc(b.businessName||'CarePoint Dental & Medical')+'</strong><small>'+esc(b.tagline||'DENTAL · MEDICAL · FAMILY CARE')+'</small></span></a><nav>';
 if(ok('home'))html+='<a href="#home">Home</a>';if(ok('services'))html+='<a href="#services">Services</a>';if(ok('doctors'))html+='<a href="#doctors">Doctors</a>';if(ok('facilities'))html+='<a href="#facilities">Facilities</a>';if(ok('gallery'))html+='<a href="#gallery">Gallery</a>';if(ok('reviews'))html+='<a href="#reviews">Reviews</a>';if(ok('appointment'))html+='<a href="#appointment">Book</a>';
 html+='</nav><div class="medical-01-actions">'+(ok('whatsapp')&&c.whatsapp?'<a class="medical-01-mini" target="_blank" href="'+wa(c.whatsapp)+'">WhatsApp</a>':'')+'<a class="template-admin-link" href="admin.html?template=medical-01">Admin</a></div></header>';
 if(ok('home'))html+='<section id="home" class="medical-01-hero"><div class="medical-01-hero-img"><img src="'+esc(d.hero||'')+'" alt="'+esc(b.businessName||'Center')+'"></div><div class="medical-01-hero-over"></div><div class="medical-01-hero-copy"><span class="medical-01-eyebrow">DENTAL · MEDICAL · FAMILY CARE</span><h1>'+esc(h.title||'Care that starts with listening.')+'</h1><p>'+esc(h.text||'')+'</p><div class="medical-01-hero-btns">'+(ok('appointment')?'<a class="medical-01-btn primary" href="#appointment">Book an appointment <span>↗</span></a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="medical-01-btn ghost" target="_blank" href="'+wa(c.whatsapp)+'">WhatsApp the centre <span>↗</span></a>':'')+'</div></div><div class="medical-01-hero-hours"><small>OPENING HOURS</small><strong>'+esc(hours.weekdays||'Add weekday hours')+'</strong><span>'+esc(hours.weekends||'Add weekend hours')+'</span></div></section>';
 if(ok('about')&&s.showAbout!==false)html+='<section id="about" class="medical-01-section medical-01-about"><div class="medical-01-side"><span class="medical-01-eyebrow">ABOUT THE CENTRE</span><span>01</span></div><div><h2>'+esc(b.businessName||'Your Center')+' brings dental and general care into a clear, welcoming visit experience.</h2><p>'+esc(b.about||'Tell your story in Admin > Business.')+'</p><div class="medical-01-sign"><strong>'+esc(b.ownerName||'Medical Director')+'</strong><span>Medical Director / Founder</span></div></div></section>';
 if(ok('services')&&s.showServices!==false)html+='<section id="services" class="medical-01-section medical-01-services"><div class="medical-01-head"><div><span class="medical-01-eyebrow">SERVICES & TREATMENTS</span><h2>Care, clearly explained.</h2></div><p>List consultations and treatments with the information patients need before booking.</p></div><div class="medical-01-service-grid">'+services.map((x,i)=>'<article class="'+(x.featured?'featured':'')+'"><div class="medical-01-service-img">'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name)+'">':'')+'<span>0'+(i+1)+'</span></div><div class="medical-01-service-body"><small>'+esc(x.category||'CARE')+' · '+esc(x.duration||'')+'</small><h3>'+esc(x.name||'Service')+'</h3><p>'+esc(x.description||'')+'</p><div><strong>'+esc(x.fee||'Ask centre')+'</strong><button type="button" class="medical-01-line" data-book-service="'+esc(x.name)+'">Request ↗</button></div></div></article>').join('')+'</div></section>';
 if(ok('doctors')&&s.showDoctors!==false)html+='<section id="doctors" class="medical-01-section medical-01-doctors"><div class="medical-01-head"><div><span class="medical-01-eyebrow">DOCTORS & SPECIALISTS</span><h2>Meet the care team.</h2></div></div><div class="medical-01-doctor-grid">'+doctors.map((x,i)=>'<article><div class="medical-01-doctor-img">'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name)+'">':'')+'<span>0'+(i+1)+'</span></div><div class="medical-01-doctor-body"><small>'+esc(x.role||'Consultant')+'</small><h3>'+esc(x.name||'Doctor')+'</h3><strong>'+esc(x.qualification||'')+'</strong><p>'+esc(x.bio||'')+'</p><button type="button" class="medical-01-line" data-book-doctor="'+esc(x.name)+'">Choose doctor ↗</button></div></article>').join('')+'</div></section>';
 if(ok('facilities')&&s.showFacilities!==false)html+='<section id="facilities" class="medical-01-section medical-01-facilities"><div class="medical-01-side"><span class="medical-01-eyebrow">FACILITIES & CARE</span><span>04</span></div><div><h2>A comfortable space for practical care.</h2><div class="medical-01-facility-grid">'+fac.map((x,i)=>'<article><span>0'+(i+1)+'</span><h3>'+esc(x.title)+'</h3><p>'+esc(x.text)+'</p></article>').join('')+'</div></div></section>';
 if(ok('gallery')&&s.showGallery!==false)html+='<section id="gallery" class="medical-01-section medical-01-gallery"><div class="medical-01-head"><div><span class="medical-01-eyebrow">CENTER GALLERY</span><h2>See the space before you visit.</h2></div></div><div class="medical-01-gallery-grid">'+gallery.map(x=>'<button type="button" class="medical-01-gallery-item" data-gallery="'+esc(x.image)+'"><img src="'+esc(x.image)+'" alt="'+esc(x.title)+'"><span>'+esc(x.title)+'</span></button>').join('')+'</div></section>';
 if(ok('reviews')&&s.showReviews!==false)html+='<section id="reviews" class="medical-01-section medical-01-reviews"><div><span class="medical-01-eyebrow">PATIENT REVIEWS</span><h2>Good care is remembered.</h2></div><div class="medical-01-review-grid">'+reviews.map(x=>'<article><b>'+'★'.repeat(Number(x.rating)||0)+'</b><p>“'+esc(x.text)+'”</p><strong>'+esc(x.name||'Patient')+'</strong></article>').join('')+'</div></section>';
 if(ok('faq')&&s.showFAQ!==false)html+='<section id="faq" class="medical-01-section medical-01-faq"><div class="medical-01-side"><span class="medical-01-eyebrow">FAQ</span><span>07</span></div><div class="medical-01-faq-list">'+faq.map((x,i)=>'<article><button type="button" data-faq aria-expanded="false"><span>0'+(i+1)+'</span>'+esc(x.question)+'<b>+</b></button><div data-answer hidden><p>'+esc(x.answer)+'</p></div></article>').join('')+'</div></section>';
 if(ok('appointment')&&s.showAppointment!==false)html+='<section id="appointment" class="medical-01-appointment"><div class="medical-01-appointment-copy"><span class="medical-01-eyebrow">APPOINTMENT BOOKING</span><h2>'+esc(a.heading||'Book a visit that fits your day.')+'</h2><p>'+esc(a.text||'')+'</p><div class="medical-01-contact-stack">'+(c.phone?'<a href="tel:'+esc(c.phone)+'">'+esc(c.phone)+'</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':'')+'</div></div><form id="medical-01Form" class="medical-01-form"><label><span>Name</span><input name="name" required></label><label><span>Phone</span><input name="phone" required></label><label><span>Email</span><input name="email" type="email"></label><label><span>Service</span><select name="service"><option value="">Choose</option>'+services.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label><span>Preferred doctor</span><select name="doctor"><option value="">Any available</option>'+doctors.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label><span>Date</span><input name="date" type="date"></label><label><span>Time</span><input name="time" type="time"></label><label class="medical-01-wide"><span>Notes</span><textarea name="notes" rows="4" placeholder="Share a practical note for the centre."></textarea></label><div class="medical-01-notice medical-01-wide">For medical emergencies, use your local emergency service rather than this appointment form.</div><button class="medical-01-btn primary medical-01-wide" type="submit">Request appointment <span>↗</span></button></form></section>';
 if(ok('hours')&&s.showHours!==false)html+='<section id="hours" class="medical-01-hours"><div><span class="medical-01-eyebrow">OPENING HOURS</span><h2>Plan your visit.</h2></div><div class="medical-01-hours-grid"><div><small>MONDAY – SATURDAY</small><strong>'+esc(hours.weekdays||'Add weekday hours')+'</strong></div><div><small>SUNDAY</small><strong>'+esc(hours.weekends||'Add weekend hours')+'</strong></div></div></section>';
 if(ok('location')&&s.showLocation!==false)html+='<section id="location" class="medical-01-location"><div><span class="medical-01-eyebrow">LOCATION</span><h2>Easy to find. Ready for your visit.</h2><p>'+esc(c.address||'Add your address in Admin > Contact.')+'</p></div><div class="medical-01-location-actions">'+(c.maps?'<a class="medical-01-btn ghost" target="_blank" href="'+esc(c.maps)+'">Open in Maps <span>↗</span></a>':'')+(c.phone?'<a class="medical-01-line" href="tel:'+esc(c.phone)+'">Call '+esc(c.phone)+' <span>↗</span></a>':'')+'</div></section>';
 if(ok('terms')&&s.showTerms!==false)html+='<section id="terms" class="medical-01-legal"><span class="medical-01-eyebrow">TERMS & CONDITIONS</span><p>'+esc(d.termsText||'')+'</p></section>';
 if(ok('privacy')&&s.showPrivacy!==false)html+='<section id="privacy" class="medical-01-legal light"><span class="medical-01-eyebrow">PRIVACY POLICY</span><p>'+esc(d.privacyPolicy||'')+'</p></section>';
 if(ok('contact')&&s.showContact!==false)html+='<section id="contact" class="medical-01-contact"><div><span class="medical-01-eyebrow">CONTACT</span><h2>Questions before you visit?</h2><p>'+esc(c.address||'')+'</p></div><div class="medical-01-contact-links">'+(c.phone?'<a href="tel:'+esc(c.phone)+'">Call '+esc(c.phone)+'</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':'')+(c.whatsapp?'<a target="_blank" href="'+wa(c.whatsapp)+'">WhatsApp ↗</a>':'')+'</div></section>';
 html+='<div class="medical-01-modal" hidden><div class="medical-01-modal-backdrop" data-close></div><div class="medical-01-modal-panel"><button type="button" class="medical-01-modal-close" data-close>×</button><img data-modal-img src="" alt=""></div></div><footer class="medical-01-footer"><div><span class="medical-01-mark">CP</span><div><strong>'+esc(b.businessName||'CarePoint Dental & Medical')+'</strong><small>'+esc(b.tagline||'Dental · Medical · Family Care')+'</small></div></div><div class="medical-01-footer-links">'+(c.whatsapp?'<a target="_blank" href="'+wa(c.whatsapp)+'">WhatsApp</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':'')+'</div><a class="template-admin-link" href="admin.html?template=medical-01">Admin</a></footer></div>';
 return html;
}
export function init(root,d={},selected=[]){
 const c=d.contact||{},business=d.brand?.businessName||'Medical Center',form=root.querySelector('#medical-01Form');
 const setVal=(selector,val)=>{const x=root.querySelector(selector);if(x)x.value=val||''};
 root.querySelectorAll('[data-book-service]').forEach(x=>x.addEventListener('click',()=>{setVal('select[name="service"]',x.dataset.bookService);root.querySelector('#appointment')?.scrollIntoView({behavior:'smooth'})}));
 root.querySelectorAll('[data-book-doctor]').forEach(x=>x.addEventListener('click',()=>{setVal('select[name="doctor"]',x.dataset.bookDoctor);root.querySelector('#appointment')?.scrollIntoView({behavior:'smooth'})}));
 root.querySelectorAll('[data-faq]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.parentElement.querySelector('[data-answer]'),open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));a.hidden=open;btn.classList.toggle('open',!open)}));
 const modal=root.querySelector('.medical-01-modal'),img=root.querySelector('[data-modal-img]');
 root.querySelectorAll('[data-gallery]').forEach(x=>x.addEventListener('click',()=>{img.src=x.dataset.gallery;modal.hidden=false;document.body.style.overflow='hidden'}));
 root.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>{modal.hidden=true;document.body.style.overflow=''}));
 form?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),lead={id:crypto.randomUUID(),createdAt:new Date().toLocaleString(),name:f.get('name')||'',phone:f.get('phone')||'',email:f.get('email')||'',service:f.get('service')||'',doctor:f.get('doctor')||'',date:f.get('date')||'',time:f.get('time')||'',notes:f.get('notes')||''};try{const key='sitecraft:medical-01',saved=JSON.parse(localStorage.getItem(key)||'{}');saved.leads=Array.isArray(saved.leads)?saved.leads:[];saved.leads.unshift(lead);localStorage.setItem(key,JSON.stringify(saved))}catch{}if(!safe(c.whatsapp)){alert('Please add a WhatsApp number in Admin > Contact.');return}const msg=['Hello '+business+'!','','New appointment enquiry:','Name: '+lead.name,'Phone: '+lead.phone,'Email: '+(lead.email||'Not specified'),'Service: '+(lead.service||'Not specified'),'Doctor: '+(lead.doctor||'Any available'),'Date: '+(lead.date||'Not specified'),'Time: '+(lead.time||'Not specified'),'Notes: '+(lead.notes||'')].join('\n');window.open(wa(c.whatsapp,msg),'_blank')});
}