const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
const wa=(n,msg='')=>{const p=safe(n);return p?'https://wa.me/'+p+(msg?'?text='+encodeURIComponent(msg):''):''};

export function render(d={},selected=[]){
  const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},hours=d.hours||{},booking=d.booking||{},ok=x=>selected.includes(x);
  const services=(d.services||[]).filter(x=>x.enabled!==false),team=(d.team||[]).filter(x=>x.enabled!==false),gallery=(d.gallery||[]).filter(x=>x.enabled!==false&&x.image),offers=(d.offers||[]).filter(x=>x.enabled!==false),reviews=(d.reviews||[]).filter(x=>x.enabled!==false),faq=(d.faq||[]).filter(x=>x.enabled!==false);
  const featured=services.filter(x=>x.featured), shownServices=featured.length?featured:services.slice(0,3);
  let html='<div class="site-preview salon-02">';
  html+='<header class="pulse-nav"><a class="pulse-brand" href="#home"><span class="pulse-mark">MB</span><span><strong>'+esc(b.businessName||'Maison Belle')+'</strong><small>'+esc(b.tagline||'BEAUTY & WELLNESS STUDIO')+'</small></span></a><nav>';
  if(ok('home'))html+='<a href="#home">Home</a>';if(ok('services'))html+='<a href="#services">Services</a>';if(ok('team'))html+='<a href="#team">Team</a>';if(ok('gallery'))html+='<a href="#gallery">Gallery</a>';if(ok('offers'))html+='<a href="#offers">Offers</a>';if(ok('reviews'))html+='<a href="#reviews">Reviews</a>';if(ok('booking'))html+='<a href="#booking">Book</a>';
  html+='</nav><div class="pulse-nav-actions">'+(ok('whatsapp')&&c.whatsapp?'<a class="pulse-mini" target="_blank" href="'+wa(c.whatsapp)+'">WhatsApp</a>':'')+'<a class="template-admin-link" href="admin.html?template=salon-02">Admin</a></div></header>';
  if(ok('home'))html+='<section id="home" class="pulse-hero"><div class="pulse-hero-image"><img src="'+esc(h.image||d.hero||'')+'" alt="'+esc(b.businessName||'Salon')+'"></div><div class="pulse-hero-wash"></div><div class="pulse-hero-copy"><span class="pulse-eyebrow">HAIR · SKIN · BEAUTY · WELLNESS</span><h1>'+esc(h.title||'A beautiful pause in your day.')+'</h1><p>'+esc(h.text||'')+'</p><div class="pulse-actions">'+(ok('booking')?'<a class="sal-btn dark" href="#booking">Book an appointment <span>↗</span></a>':'')+(ok('whatsapp')&&c.whatsapp?'<a class="sal-btn light" target="_blank" href="'+wa(c.whatsapp)+'">Chat on WhatsApp <span>↗</span></a>':'')+'</div></div><div class="pulse-hero-note"><span>Open today</span><strong>'+esc(hours.weekdays||'By appointment')+'</strong></div></section>';
  if(ok('about')&&s.showAbout!==false)html+='<section id="about" class="sal-section sal-about"><div class="pulse-side"><span class="pulse-eyebrow">ABOUT THE STUDIO</span><span>01</span></div><div class="pulse-about-main"><h2>'+esc(b.businessName||'Your Salon')+' is a place for good work, warm service and time well spent.</h2><p>'+esc(b.about||'Tell your story in Admin > Business.')+'</p><div class="pulse-sign"><strong>'+esc(b.ownerName||'Salon Founder')+'</strong><span>Founder / Creative Director</span></div></div></section>';
  if(ok('services')&&s.showServices!==false)html+='<section id="services" class="sal-section sal-services"><div class="pulse-head"><div><span class="pulse-eyebrow">SERVICES & PRICING</span><h2>A considered menu.</h2></div><p>Keep your most-loved services easy to browse. Everything is editable from Admin.</p></div><div class="pulse-service-grid">'+services.map((x,i)=>'<article class="'+(x.featured?'featured':'')+'"><div class="pulse-service-image">'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name||'')+'">':'')+'<span>0'+(i+1)+'</span></div><div class="pulse-service-body"><small>'+esc(x.category||'BEAUTY')+' · '+esc(x.duration||'')+'</small><h3>'+esc(x.name||'Service')+'</h3><p>'+esc(x.description||'')+'</p><div class="pulse-service-meta"><strong>'+esc(x.price||'Price on request')+'</strong><button type="button" class="pulse-line" data-book-service="'+esc(x.name||'')+'">Book <span>↗</span></button></div></div></article>').join('')+'</div></section>';
  if(ok('offers')&&s.showOffers!==false)html+='<section id="offers" class="sal-section sal-offers"><div class="pulse-head"><div><span class="pulse-eyebrow">CURRENT OFFERS</span><h2>Little extras.</h2></div><p>Update special packages, first-visit ideas and seasonal promotions from Admin.</p></div><div class="pulse-offer-grid">'+offers.map((x,i)=>'<article><span>'+esc(x.tag||'SPECIAL')+'</span><h3>'+esc(x.title||'Offer')+'</h3><p>'+esc(x.text||'')+'</p>'+(ok('booking')?'<a class="sal-line dark-link" href="#booking" data-book-service="'+esc(x.title||'')+'">Ask about this offer <b>↗</b></a>':'')+'</article>').join('')+'</div></section>';
  if(ok('gallery')&&s.showGallery!==false)html+='<section id="gallery" class="sal-section sal-gallery"><div class="pulse-head"><div><span class="pulse-eyebrow">GALLERY</span><h2>A look inside.</h2></div><p>Replace these sample photographs from the builder or Admin.</p></div><div class="pulse-gallery-grid">'+gallery.map((x,i)=>'<button type="button" class="pulse-gallery-item" data-gallery-image="'+esc(x.image)+'" aria-label="'+esc(x.title||'Gallery')+'"><img src="'+esc(x.image)+'" alt="'+esc(x.title||'')+'"><span>'+esc(x.title||'Gallery image')+'</span></button>').join('')+'</div></section>';
  if(ok('team')&&s.showTeam!==false)html+='<section id="team" class="sal-section sal-team"><div class="pulse-head"><div><span class="pulse-eyebrow">OUR TEAM</span><h2>People who take care.</h2></div></div><div class="pulse-team-grid">'+team.map(x=>'<article><div class="pulse-team-image">'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name||'')+'">':'')+'</div><div><small>'+esc(x.role||'Stylist')+'</small><h3>'+esc(x.name||'Team member')+'</h3><p>'+esc(x.bio||'')+'</p></div></article>').join('')+'</div></section>';
  if(ok('reviews')&&s.showReviews!==false)html+='<section id="reviews" class="sal-section sal-reviews"><div class="pulse-review-intro"><span class="pulse-eyebrow">CUSTOMER REVIEWS</span><h2>Kind words, honestly shared.</h2></div><div class="pulse-review-grid">'+reviews.map(x=>'<article><b>'+'★'.repeat(Number(x.rating)||0)+'</b><p>“'+esc(x.text||'')+'”</p><strong>'+esc(x.name||'Client')+'</strong></article>').join('')+'</div></section>';
  if(ok('faq')&&s.showFAQ!==false)html+='<section id="faq" class="sal-section sal-faq"><div class="pulse-side"><span class="pulse-eyebrow">FAQ</span><span>06</span></div><div class="pulse-faq-list">'+faq.map((x,i)=>'<article><button type="button" data-faq-toggle aria-expanded="false"><span>0'+(i+1)+'</span>'+esc(x.question||'Question')+'<b>+</b></button><div data-faq-answer hidden><p>'+esc(x.answer||'')+'</p></div></article>').join('')+'</div></section>';
  if(ok('booking')&&s.showBooking!==false)html+='<section id="booking" class="pulse-booking"><div class="pulse-booking-copy"><span class="pulse-eyebrow">APPOINTMENT BOOKING</span><h2>'+esc(booking.heading||'Reserve a little time for yourself.')+'</h2><p>'+esc(booking.text||'')+'</p><div class="pulse-booking-contact">'+(c.phone?'<a href="tel:'+esc(c.phone)+'">'+esc(c.phone)+'</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':'')}</div></div><form id="pulseBookingForm" class="pulse-booking-form"><label><span>Name</span><input name="name" required placeholder="Your name"></label><label><span>Phone</span><input name="phone" required placeholder="+91"></label><label><span>Email</span><input name="email" type="email" placeholder="you@example.com"></label><label><span>Service</span><select name="service"><option value="">Choose a service</option>'+services.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label><span>Preferred team member</span><select name="staff"><option value="">Any available</option>'+team.map(x=>'<option>'+esc(x.name)+'</option>').join('')+'</select></label><label><span>Preferred date</span><input name="date" type="date"></label><label><span>Preferred time</span><input name="time" type="time"></label><label class="pulse-wide"><span>Notes</span><textarea name="notes" rows="4" placeholder="Colour preference, event date, anything we should know."></textarea></label><button class="sal-btn dark sal-wide" type="submit">Request appointment <span>↗</span></button></form></section>';
  if(ok('hours')&&s.showHours!==false)html+='<section id="hours" class="pulse-hours"><div><span class="pulse-eyebrow">OPENING HOURS</span><h2>Come when it suits you.</h2></div><div class="pulse-hours-grid"><div><small>MONDAY – FRIDAY</small><strong>'+esc(hours.weekdays||'Add weekday hours')+'</strong></div><div><small>WEEKEND</small><strong>'+esc(hours.weekends||'Add weekend hours')+'</strong></div></div></section>';
  if(ok('location')&&s.showLocation!==false)html+='<section id="location" class="pulse-location"><div><span class="pulse-eyebrow">LOCATION</span><h2>Easy to find. Easy to return to.</h2><p>'+esc(c.address||'Add your address in Admin > Contact.')+'</p></div><div class="pulse-location-actions">'+(c.maps?'<a class="sal-btn light" target="_blank" href="'+esc(c.maps)+'">Open in Maps <span>↗</span></a>':'')+(c.phone?'<a class="sal-line dark-link" href="tel:'+esc(c.phone)+'">Call '+esc(c.phone)+' <span>↗</span></a>':'')+'</div></section>';
  if(ok('terms')&&s.showTerms!==false)html+='<section id="terms" class="pulse-legal"><span class="pulse-eyebrow">TERMS & CONDITIONS</span><p>'+esc(d.termsText||'')+'</p></section>';
  if(ok('privacy')&&s.showPrivacy!==false)html+='<section id="privacy" class="sal-legal light"><span class="pulse-eyebrow">PRIVACY POLICY</span><p>'+esc(d.privacyPolicy||'')+'</p></section>';
  if(ok('contact')&&s.showContact!==false)html+='<section id="contact" class="pulse-contact"><div><span class="pulse-eyebrow">CONTACT</span><h2>Let’s make a plan.</h2><p>'+esc(c.address||'')+'</p></div><div class="pulse-contact-links">'+(c.phone?'<a href="tel:'+esc(c.phone)+'">Call '+esc(c.phone)+'</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':'')+(c.whatsapp?'<a target="_blank" href="'+wa(c.whatsapp)+'">WhatsApp ↗</a>':'')+'</div></section>';
  html+='<div class="sal-modal" id="pulseGalleryModal" hidden><div class="sal-modal-backdrop" data-close-pulse-modal></div><div class="sal-modal-panel"><button type="button" class="sal-modal-close" data-close-pulse-modal>×</button><img id="pulseModalImage" src="" alt=""></div></div>';
  html+='<footer class="sal-footer"><div><span class="pulse-mark">MB</span><div><strong>'+esc(b.businessName||'Maison Belle')+'</strong><small>'+esc(b.tagline||'Beauty & Wellness Studio')+'</small></div></div><div class="sal-footer-links">'+(c.whatsapp?'<a target="_blank" href="'+wa(c.whatsapp)+'">WhatsApp</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">'+esc(c.email)+'</a>':'')+'</div><a class="template-admin-link" href="admin.html?template=salon-02">Admin</a></footer></div>';
  return html;
}
export function init(root,d={},selected=[]){
  const c=d.contact||{},business=d.brand?.businessName||'Salon',form=root.querySelector('#pulseBookingForm');
  const setService=v=>{const s=root.querySelector('select[name="service"]');if(s)s.value=v};
  root.querySelectorAll('[data-book-service]').forEach(x=>x.addEventListener('click',()=>setService(x.dataset.bookService)));
  root.querySelectorAll('[data-faq-toggle]').forEach(btn=>btn.addEventListener('click',()=>{const a=btn.parentElement?.querySelector('[data-faq-answer]'),open=btn.getAttribute('aria-expanded')==='true';btn.setAttribute('aria-expanded',String(!open));if(a)a.hidden=open;btn.classList.toggle('open',!open)}));
  const modal=root.querySelector('#pulseGalleryModal'),img=root.querySelector('#pulseModalImage');
  root.querySelectorAll('[data-gallery-image]').forEach(btn=>btn.addEventListener('click',()=>{if(!modal||!img)return;img.src=btn.dataset.galleryImage;modal.hidden=false;document.body.style.overflow='hidden'}));
  root.querySelectorAll('[data-close-pulse-modal]').forEach(x=>x.addEventListener('click',()=>{if(modal)modal.hidden=true;document.body.style.overflow=''}));
  form?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),lead={id:crypto.randomUUID(),createdAt:new Date().toLocaleString(),name:f.get('name')||'',phone:f.get('phone')||'',email:f.get('email')||'',service:f.get('service')||'',staff:f.get('staff')||'',date:f.get('date')||'',time:f.get('time')||'',notes:f.get('notes')||''};try{const key='sitecraft:salon-02',saved=JSON.parse(localStorage.getItem(key)||'{}');saved.leads=Array.isArray(saved.leads)?saved.leads:[];saved.leads.unshift(lead);localStorage.setItem(key,JSON.stringify(saved))}catch{}if(!safe(c.whatsapp)){alert('Please add a WhatsApp number in Admin > Contact.');return}const msg=['Hello '+business+'!','','New appointment enquiry:','Name: '+lead.name,'Phone: '+lead.phone,'Email: '+(lead.email||'Not specified'),'Service: '+(lead.service||'Not specified'),'Preferred staff: '+(lead.staff||'Any available'),'Date: '+(lead.date||'Not specified'),'Time: '+(lead.time||'Not specified'),'Notes: '+(lead.notes||'')].join('\\n');window.open(wa(c.whatsapp,msg),'_blank')});
}
