const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function render(d={},selected=[]){
 const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},projects=(d.projects||[]).filter(x=>x.enabled!==false),skills=(d.skills||[]).filter(x=>x.enabled!==false);
 const ok=x=>selected.includes(x);
 return '<div class="site-preview port1"><header><strong>'+esc(b.businessName||'Your Name')+'</strong><nav>'+(ok('about')?'<a href="#about">About</a>':'')+(ok('skills')?'<a href="#skills">Skills</a>':'')+(ok('projects')?'<a href="#projects">Projects</a>':'')+(ok('contact')?'<a href="#contact">Contact</a>':'')+'</nav><a class="template-admin-link" href="admin.html?template=portfolio-01">Admin</a></header>'+
 (ok('home')?'<section class="hero"><img src="'+esc(d.hero||'')+'" alt=""><div><small>'+esc(b.ownerName||'PORTFOLIO')+'</small><h1>'+esc(h.title||'A portfolio that puts your work first.')+'</h1><p>'+esc(h.text||'')+'</p>'+(b.resumeUrl?'<a class="btn" target="_blank" href="'+esc(b.resumeUrl)+'">View resume</a>':'')+'</div></section>':'')+
 (ok('about')&&s.showAbout!==false?'<section id="about"><small>ABOUT ME</small><h2>'+esc(b.about||'Introduce yourself, your experience and what makes your work different.')+'</h2></section>':'')+
 (ok('skills')?'<section id="skills" class="soft"><small>CAPABILITIES</small><h2>Skills & tools</h2><div class="skill-grid">'+skills.map(x=>'<span>'+esc(x.name||'Skill')+'<small>'+esc(x.level||'')+'</small></span>').join('')+'</div></section>':'')+
 (ok('projects')?'<section id="projects"><small>SELECTED WORK</small><h2>Projects</h2><div class="project-grid">'+projects.map(x=>'<article><img src="'+esc(x.image||'')+'" alt=""><div><span>'+esc(x.role||'Project')+'</span><h3>'+esc(x.name||'Project')+'</h3><p>'+esc(x.description||'')+'</p></div></article>').join('')+'</div></section>':'')+
 (ok('contact')&&s.showContact!==false?'<section id="contact"><small>CONTACT</small><h2>Let’s work together.</h2><p>'+esc(c.email||'')+' · '+esc(c.call||'')+' · '+esc(c.location||'')+'</p><div>'+(c.maps?'<a class="btn dark" target="_blank" href="'+esc(c.maps)+'">Location</a>':'')+(c.whatsapp?'<a class="btn" target="_blank" href="https://wa.me/'+String(c.whatsapp).replace(/\D/g,'')+'">WhatsApp</a>':'')+'</div></section>':'')+
 '<footer>© '+new Date().getFullYear()+' '+esc(b.businessName||'Your Name')+'</footer></div>';
}