const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=v=>String(v??'').replace(/[^0-9]/g,'');
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const money=(cur,n)=>esc(cur||'₹')+new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Math.max(0,num(n)));
const list=v=>Array.isArray(v)?v.filter(x=>x&&x.enabled!==false):[];
export function render(d={},selected=[]){
  const b=d.brand||{},h=d.home||{},c=d.contact||{},s=d.settings||{},cake=d.cake||{},del=d.delivery||{},party=d.party||{},os=d.orderSettings||{},ok=x=>selected.includes(x);
  const menu=list(d.menu),offers=list(d.offers),gallery=list(d.gallery),reviews=list(d.reviews),services=list(d.services),hygiene=list(d.hygiene),faq=list(d.faq),hours=list(d.hours),slots=list(del.slots),partyPackages=list(party.packages),bases=list(cake.bases),sizes=list(cake.sizes),fillings=list(cake.fillings),toppings=list(cake.toppings);
  const cats=[...new Set(menu.map(x=>x.category).filter(Boolean))];
  let html='<div class="site-preview cloudkitchen-01">';
  html+='<header class="ck-nav"><a class="ck-brand" href="#home"><span class="ck-mark">CK</span><span><strong>'+esc(b.businessName||"Your Kitchen")+'</strong><small>'+esc(b.tagline||"DIRECT ORDERS · FRESHLY MADE")+'</small></span></a><nav>';
  if(ok('home'))html+='<a href="#home">Home</a>';
  if(ok('menu'))html+='<a href="#menu">Menu</a>';
  if(ok('cake'))html+='<a href="#cake">Custom Cake</a>';
  if(ok('delivery'))html+='<a href="#delivery">Delivery</a>';
  if(ok('party'))html+='<a href="#party">Party Orders</a>';
  if(ok('order'))html+='<a href="#order">Order</a>';
  html+='</nav><div class="ck-nav-actions">'+(ok('whatsapp')&&c.whatsapp?'<a class="ck-mini ck-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+'<a class="template-admin-link" href="admin.html?template=cloudkitchen-01">Admin</a></div></header>';

  if(ok('home')&&s.showHome!==false)html+='<section id="home" class="ck-hero"><div class="ck-hero-copy"><span class="ck-kicker">DIRECT FROM OUR KITCHEN</span><h1>'+esc(h.title||"Your cravings. Delivered direct.")+'</h1><p>'+esc(h.text||"Fresh food and celebration bakes, ordered directly.")+'</p><div class="ck-actions">'+(ok('order')?'<a class="ck-btn solid" href="#order">Start an order <span>↗</span></a>':'')+(ok('cake')?'<a class="ck-btn light" href="#cake">Build a cake <span>＋</span></a>':'')+'</div><div class="ck-hero-note"><span>DIRECT ORDER</span><strong>No marketplace detour.</strong></div></div><div class="ck-hero-media">'+(d.heroVideo?'<video autoplay muted loop playsinline poster="'+esc(d.hero||'')+'"><source src="'+esc(d.heroVideo)+'" type="video/mp4"></video>':'<img src="'+esc(d.hero||'')+'" alt="'+esc(b.businessName||"Kitchen")+'">')+'<div class="ck-hero-chip"><span>FRESH</span><strong>Made to order</strong></div></div></section>';

  if(ok('menu')&&s.showMenu!==false)html+='<section id="menu" class="ck-section"><div class="ck-head split"><div><span class="ck-kicker">TODAY’S MENU</span><h2>Good food, straight from the kitchen.</h2></div><p>Browse by category, add items to your cart and continue to the direct-order form.</p></div><div class="ck-cat-row"><button class="ck-cat active" data-menu-cat="all">All</button>'+cats.map(x=>'<button class="ck-cat" data-menu-cat="'+esc(x)+'">'+esc(x)+'</button>').join('')+'</div><div class="ck-menu-grid" id="ckMenuGrid">'+menu.map(x=>'<article class="ck-menu-card" data-category="'+esc(x.category||'')+'"><img src="'+esc(x.image||'')+'" alt="'+esc(x.name||'Menu item')+'"><div class="ck-menu-body"><div class="ck-menu-meta"><span>'+esc(x.category||'')+'</span><span>'+esc(x.veg?'VEG':'NON-VEG')+'</span></div><h3>'+esc(x.name||'Item')+'</h3><p>'+esc(x.description||'')+'</p><div class="ck-menu-foot"><strong>'+money(os.currency||'₹',x.price||0)+'</strong><button class="ck-add" data-menu-id="'+esc(x.id)+'">Add to order ＋</button></div></div></article>').join('')+'</div></section>';

  if(ok('cake'))html+='<section id="cake" class="ck-section ck-cake"><div class="ck-head split"><div><span class="ck-kicker">CAKE CUSTOMIZER</span><h2>'+esc(cake.title||"Build your cake your way.")+'</h2></div><p>Choose size, base, filling and toppings. The live total updates before you add the cake to your order.</p></div><div class="ck-cake-grid"><div class="ck-cake-form"><label>Size<select id="ckCakeSize">'+sizes.map((x,i)=>'<option value="'+esc(x.id)+'" '+(i===1?'selected':'')+' data-price="'+num(x.price)+'">'+esc(x.name)+'</option>').join('')+'</select></label><label>Cake base<select id="ckCakeBase">'+bases.map((x,i)=>'<option value="'+esc(x.id)+'" '+(i===0?'selected':'')+' data-price="'+num(x.price)+'">'+esc(x.name)+' '+(x.price?'(+'+money(os.currency||'₹',x.price)+')':'')+'</option>').join('')+'</select></label><label>Filling<select id="ckCakeFilling">'+fillings.map((x,i)=>'<option value="'+esc(x.id)+'" '+(i===0?'selected':'')+' data-price="'+num(x.price)+'">'+esc(x.name)+' '+(x.price?'(+'+money(os.currency||'₹',x.price)+')':'')+'</option>').join('')+'</select></label><div><span class="ck-label">Toppings / add-ons</span><div class="ck-option-grid">'+toppings.map(x=>'<label class="ck-option"><input class="ckCakeTop" type="checkbox" value="'+esc(x.id)+'" data-price="'+num(x.price)+'"><span>✓</span><strong>'+esc(x.name)+'</strong><small>'+(x.price?'+ '+money(os.currency||'₹',x.price):'Included')+'</small></label>').join('')+'</div></div><label>Cake message<input id="ckCakeMessage" maxlength="60" placeholder="Happy Birthday!"></label><div class="ck-cake-result"><span>Estimated cake price</span><strong id="ckCakeTotal">'+money(os.currency||'₹',0)+'</strong><button class="ck-btn solid" type="button" id="ckAddCake">Add custom cake to order <span>＋</span></button></div></div><div class="ck-cake-visual"><img src="'+esc((gallery[0]?.image)||d.hero||'')+'" alt="Custom cake"><div><span>Custom</span><strong>Made for your occasion.</strong><p>Pricing is indicative until the kitchen confirms the exact design, weight, topper and delivery details.</p></div></div></div></section>';

  if(ok('delivery')&&s.showDelivery!==false)html+='<section id="delivery" class="ck-section ck-delivery"><div class="ck-head split"><div><span class="ck-kicker">DELIVERY</span><h2>Choose a slot that works for you.</h2></div><p>'+esc(del.sameDayNote||"Delivery availability depends on slot capacity and area.")+'<br>'+esc(del.deliveryFeeText||c.deliveryArea||"Delivery fee confirmed by area.")+'</p></div><div class="ck-delivery-grid"><div><span class="ck-label">Available slots</span><div class="ck-slot-grid">'+slots.map(x=>'<button type="button" class="ck-slot" data-slot="'+esc(x.label)+'">'+esc(x.label)+'</button>').join('')+'</div></div><div class="ck-area-card"><span>DELIVERY AREA</span><strong>'+esc(c.deliveryArea||"Set your delivery area in Admin.")+'</strong><p>Pickup location and service-area notes can be edited from the Admin panel.</p></div></div></section>';

  if(ok('party')&&s.showParty!==false)html+='<section id="party" class="ck-section ck-party"><div class="ck-head split"><div><span class="ck-kicker">PARTY & BULK ORDERS</span><h2>From family celebrations to office gatherings.</h2></div><p>'+esc(party.leadTimeText||"Share your guest count and requirements for a tailored order.")+'</p></div><div class="ck-party-grid">'+partyPackages.map((x,i)=>'<article><span>0'+(i+1)+'</span><h3>'+esc(x.name||"Party order")+'</h3><strong>'+esc(x.guests||"Custom")+' guests</strong><p>'+esc(x.note||"")+'</p><a class="ck-link" href="#order" data-party="'+esc(x.name||'')+'">Plan this order ↗</a></article>').join('')+'</div><div class="ck-capacity"><span>CAPACITY</span><strong>'+esc(party.capacityText||"Party orders welcome")+'</strong></div></section>';

  if(ok('order')&&s.showOrder!==false)html+='<section id="order" class="ck-section ck-order"><div class="ck-head split"><div><span class="ck-kicker">DIRECT ORDER</span><h2>Your order, one message away.</h2></div><p>Items added above appear in your live cart. Choose delivery details and send the confirmed request directly to the kitchen.</p></div><div class="ck-order-grid"><aside class="ck-cart"><div class="ck-cart-head"><strong>Your order</strong><span id="ckCartCount">0 items</span></div><div id="ckCartItems" class="ck-cart-items"><div class="ck-empty-cart">Add menu items or a custom cake to start.</div></div><div class="ck-cart-total"><span>Total</span><strong id="ckCartTotal">'+money(os.currency||'₹',0)+'</strong></div></aside><form id="ckOrderForm" class="ck-form"><div class="ck-form-grid"><label>Name<input name="name" required placeholder="Your name"></label><label>Phone<input name="phone" required type="tel" placeholder="+91"></label><label>Email<input name="email" type="email" placeholder="you@example.com"></label><label>Order type<select name="orderType" id="ckOrderType"><option>Regular Order</option><option>Custom Cake</option><option>Party / Bulk Order</option></select></label><label>Delivery / Pickup Date<input name="deliveryDate" type="date"></label><label>Delivery Slot<select name="deliverySlot" id="ckDeliverySlot"><option value="">Choose a slot</option>'+slots.map(x=>'<option>'+esc(x.label)+'</option>').join('')+'</select></label><label class="full">Delivery / Pickup Location<input name="location" required placeholder="Area, landmark, full address"></label><label>Party Guests<input name="partyGuests" type="number" min="0" placeholder="e.g. 40"></label><label>Preferred contact<select name="contactMode"><option>WhatsApp</option><option>Call</option></select></label></div><label>Order / Message<textarea name="message" id="ckOrderMessage" placeholder="Special instructions, cake message, delivery notes, etc."></textarea></label><div class="ck-form-foot"><span id="ckOrderNotice" class="ck-notice"></span><button class="ck-btn solid" type="submit">Send order to kitchen <span>↗</span></button></div></form></div></section>';

  if(ok('offers')&&s.showOffers!==false)html+='<section class="ck-section ck-offers"><div class="ck-head"><span class="ck-kicker">OFFERS</span><h2>Make your order a little more rewarding.</h2></div><div class="ck-offer-grid">'+offers.map(x=>'<article><span>✦</span><h3>'+esc(x.title)+'</h3><p>'+esc(x.text||'')+'</p></article>').join('')+'</div></section>';

  if(ok('services')&&s.showServices!==false)html+='<section class="ck-section ck-services"><div class="ck-head"><span class="ck-kicker">WHAT WE MAKE</span><h2>More than a menu — made for everyday and celebrations.</h2></div><div class="ck-service-grid">'+services.map((x,i)=>'<article><span class="ck-service-icon">'+esc(x.icon||"•")+'</span><small>0'+(i+1)+'</small><h3>'+esc(x.name)+'</h3><p>'+esc(x.description||'')+'</p></article>').join('')+'</div></section>';

  if(ok('gallery')&&s.showGallery!==false)html+='<section class="ck-section"><div class="ck-head split"><div><span class="ck-kicker">FROM THE KITCHEN</span><h2>See what is coming out fresh.</h2></div><p>Replace sample images from the Admin panel with your own food, cake and packaging photos.</p></div><div class="ck-gallery">'+gallery.map(x=>'<figure><img src="'+esc(x.image||'')+'" alt="'+esc(x.title||'')+'"><figcaption>'+esc(x.title||'')+'</figcaption></figure>').join('')+'</div></section>';

  if(ok('reviews')&&s.showReviews!==false)html+='<section class="ck-section ck-reviews"><div class="ck-head"><span class="ck-kicker">CUSTOMER NOTES</span><h2>What direct-order customers say.</h2></div><div class="ck-review-grid">'+reviews.map(x=>'<article>'+(x.image?'<img src="'+esc(x.image)+'" alt="'+esc(x.name||'Customer')+'">':'')+'<div class="ck-stars">'+('★'.repeat(Math.max(1,Math.min(5,num(x.rating)||5))))+'</div><p>“'+esc(x.text||'')+'”</p><strong>'+esc(x.name||'Customer')+'</strong></article>').join('')+'</div></section>';

  if(ok('about')&&s.showAbout!==false)html+='<section class="ck-section ck-about"><div class="ck-head split"><div><span class="ck-kicker">ABOUT THE KITCHEN</span><h2>Small-batch thinking, direct communication.</h2></div><p>'+esc(b.about||"Tell customers how the kitchen started and what you care about.")+'</p></div><div class="ck-about-stats">'+(d.aboutStats||[]).filter(x=>x.enabled!==false).map(x=>'<div><strong>'+esc(x.value||'')+'</strong><span>'+esc(x.label||'')+'</span></div>').join('')+'</div></section>';

  if(ok('hygiene')&&s.showHygiene!==false)html+='<section class="ck-section ck-hygiene"><div class="ck-head split"><div><span class="ck-kicker">KITCHEN TRUST</span><h2>Show the standards behind the food.</h2></div><p>Only publish safety, hygiene, registration, ingredient and packaging claims that are accurate for your business.</p></div><div class="ck-hygiene-grid">'+hygiene.map(x=>'<article><span>✓</span><h3>'+esc(x.title||'Trust')+'</h3><p>'+esc(x.text||'')+'</p></article>').join('')+'</div></section>';

  if(ok('faq')&&s.showFAQ!==false)html+='<section class="ck-section"><div class="ck-head"><span class="ck-kicker">FAQ</span><h2>Before you place the order.</h2></div><div class="ck-faq">'+faq.map(x=>'<details><summary>'+esc(x.question||"Question")+'<span>+</span></summary><p>'+esc(x.answer||"")+'</p></details>').join('')+'</div></section>';

  if(ok('hours')||ok('location')||ok('social'))html+='<section class="ck-section ck-contact"><div class="ck-contact-grid"><div>'+((ok('location'))?'<span class="ck-kicker">PICKUP / KITCHEN</span><h2>'+esc(b.businessName||"Your Kitchen")+'</h2><p>'+esc(c.address||"Add pickup address here.")+'</p>':'')+(ok('hours')?'<p class="ck-contact-hours">'+esc(c.hoursText||"See opening hours below.")+'</p>':'')+(ok('call')&&c.phone?'<a class="ck-link" href="tel:'+safe(c.phone)+'">Call '+esc(c.phone)+' ↗</a>':'')+'</div>'+(ok('location')&&c.maps?'<a class="ck-map-card" target="_blank" href="'+esc(c.maps)+'"><span>OPEN MAP</span><strong>Get pickup directions ↗</strong><small>'+esc(c.deliveryArea||"View service area")+'</small></a>':'')+'</div></section>';

  if(ok('hours'))html+='<section class="ck-section ck-hours"><div class="ck-head split"><div><span class="ck-kicker">OPENING HOURS</span><h2>Order while the kitchen is open.</h2></div></div><div class="ck-hours-list">'+hours.map(x=>'<div><strong>'+esc(x.day||"Day")+'</strong><span>'+esc(x.enabled!==false?(x.open||"")+" — "+(x.close||""):"Closed")+'</span></div>').join('')+'</div></section>';

  if(ok('social')&&s.showSocial!==false)html+='<section class="ck-section ck-social"><div><span class="ck-kicker">FOLLOW THE KITCHEN</span><h2>See new bakes, specials and behind-the-scenes updates.</h2></div><div class="ck-social-links">'+(c.instagram?'<a class="ck-btn light" target="_blank" href="'+esc(c.instagram)+'">Instagram ↗</a>':'')+(d.social?.facebook?'<a class="ck-btn light" target="_blank" href="'+esc(d.social.facebook)+'">Facebook ↗</a>':'')+(d.social?.youtube?'<a class="ck-btn light" target="_blank" href="'+esc(d.social.youtube)+'">YouTube ↗</a>':'')+'</div></section>';

  if(ok('terms')||ok('privacy'))html+='<section class="ck-legal">'+(ok('terms')?'<details><summary>Terms & Order Policy</summary><p>'+esc(d.termsText||'')+'</p></details>':'')+(ok('privacy')?'<details><summary>Privacy Policy</summary><p>'+esc(d.privacyPolicy||'')+'</p></details>':'')+'</section>';

  html+='<footer class="ck-footer"><div><strong>'+esc(b.businessName||"Your Kitchen")+'</strong><span>'+esc(b.tagline||"")+'</span></div><div>'+(c.phone?'<a href="tel:'+safe(c.phone)+'">Call</a>':'')+(ok('whatsapp')&&c.whatsapp?'<a target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp</a>':'')+(c.email?'<a href="mailto:'+esc(c.email)+'">Email</a>':'')+'</div></footer>';
  if(ok('whatsapp')&&c.whatsapp)html+='<a class="ck-float-wa" target="_blank" href="https://wa.me/'+safe(c.whatsapp)+'">WhatsApp ↗</a>';
  html+='</div>';
  return html;
}
export function init(root,d={}){
  const menu=list(d.menu),slots=list(d.delivery?.slots),currency=d.orderSettings?.currency||'₹';
  let cart=[];
  const moneyLocal=n=>currency+new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Math.max(0,num(n)));
  const renderCart=()=>{
    const box=root.querySelector('#ckCartItems'),count=root.querySelector('#ckCartCount'),totalEl=root.querySelector('#ckCartTotal');
    const total=cart.reduce((s,x)=>s+x.price*x.qty,0);
    if(count)count.textContent=cart.reduce((s,x)=>s+x.qty,0)+' item'+(cart.reduce((s,x)=>s+x.qty,0)===1?'':'s');
    if(totalEl)totalEl.textContent=moneyLocal(total);
    if(box)box.innerHTML=cart.length?cart.map((x,i)=>'<div class="ck-cart-item"><div><strong>'+esc(x.name)+'</strong><small>'+esc(x.meta||"")+'</small></div><div class="ck-cart-actions"><button type="button" data-cart-dec="'+i+'">−</button><span>'+x.qty+'</span><button type="button" data-cart-inc="'+i+'">+</button><strong>'+moneyLocal(x.price*x.qty)+'</strong><button class="ck-remove" type="button" data-cart-del="'+i+'">×</button></div></div>').join(''):'<div class="ck-empty-cart">Add menu items or a custom cake to start.</div>';
    box?.querySelectorAll('[data-cart-inc]').forEach(b=>b.onclick=()=>{cart[Number(b.dataset.cartInc)].qty++;renderCart()});
    box?.querySelectorAll('[data-cart-dec]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.cartDec);cart[i].qty=Math.max(0,cart[i].qty-1);if(!cart[i].qty)cart.splice(i,1);renderCart()});
    box?.querySelectorAll('[data-cart-del]').forEach(b=>{b.onclick=()=>{cart.splice(Number(b.dataset.cartDel),1);renderCart()}});
  };
  root.querySelectorAll('.ck-add').forEach(b=>b.onclick=()=>{const x=menu.find(m=>m.id===b.dataset.menuId);if(!x)return;const found=cart.find(i=>i.id===x.id);if(found)found.qty++;else cart.push({id:x.id,name:x.name,price:num(x.price),qty:1,meta:x.category||"Menu item"});renderCart();root.querySelector('#order')?.scrollIntoView({behavior:'smooth'})});
  root.querySelectorAll('[data-menu-cat]').forEach(b=>b.onclick=()=>{root.querySelectorAll('.ck-cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');const cat=b.dataset.menuCat;root.querySelectorAll('.ck-menu-card').forEach(card=>card.hidden=cat!=='all'&&card.dataset.category!==cat)});
  const getSelectedPrice=id=>{const s=root.querySelector(id);return num(s?.selectedOptions?.[0]?.dataset?.price||0)};
  const updateCake=()=>{
    const total=getSelectedPrice('#ckCakeSize')+getSelectedPrice('#ckCakeBase')+getSelectedPrice('#ckCakeFilling')+[...root.querySelectorAll('.ckCakeTop:checked')].reduce((s,x)=>s+num(x.dataset.price),0);
    const out=root.querySelector('#ckCakeTotal');if(out)out.textContent=moneyLocal(total);
  };
  ['#ckCakeSize','#ckCakeBase','#ckCakeFilling'].forEach(sel=>root.querySelector(sel)?.addEventListener('change',updateCake));
  root.querySelectorAll('.ckCakeTop').forEach(x=>x.addEventListener('change',updateCake));
  updateCake();
  root.querySelector('#ckAddCake')?.addEventListener('click',()=>{
    const size=root.querySelector('#ckCakeSize')?.selectedOptions?.[0],base=root.querySelector('#ckCakeBase')?.selectedOptions?.[0],filling=root.querySelector('#ckCakeFilling')?.selectedOptions?.[0];
    const tops=[...root.querySelectorAll('.ckCakeTop:checked')].map(x=>x.parentElement?.querySelector('strong')?.textContent||'').filter(Boolean);
    const message=root.querySelector('#ckCakeMessage')?.value||'';
    const price=getSelectedPrice('#ckCakeSize')+getSelectedPrice('#ckCakeBase')+getSelectedPrice('#ckCakeFilling')+[...root.querySelectorAll('.ckCakeTop:checked')].reduce((s,x)=>s+num(x.dataset.price),0);
    cart.push({id:'cake-'+Date.now(),name:'Custom Cake · '+(size?.textContent||''),price,qty:1,meta:[base?.textContent?.trim(),filling?.textContent?.trim(),tops.join(', '),message?'Message: '+message:''].filter(Boolean).join(' · ')});
    renderCart();root.querySelector('#order')?.scrollIntoView({behavior:'smooth'})
  });
  root.querySelectorAll('.ck-slot').forEach(b=>b.onclick=()=>{root.querySelectorAll('.ck-slot').forEach(x=>x.classList.remove('active'));b.classList.add('active');const s=root.querySelector('#ckDeliverySlot');if(s){s.value=b.dataset.slot;s.dispatchEvent(new Event('change'))}});
  root.querySelectorAll('[data-party]').forEach(b=>b.onclick=()=>{const f=root.querySelector('#ckOrderType');if(f){f.value='Party / Bulk Order';f.dispatchEvent(new Event('change'))}root.querySelector('#ckOrder')?.scrollIntoView?.({behavior:'smooth'})});
  const form=root.querySelector('#ckOrderForm');
  if(form)form.addEventListener('submit',ev=>{
    ev.preventDefault();
    if(!cart.length){const n=root.querySelector('#ckOrderNotice');if(n)n.textContent='Add at least one item or custom cake before sending the order.';return}
    const fd=new FormData(form),lead=Object.fromEntries(fd.entries());
    const total=cart.reduce((s,x)=>s+x.price*x.qty,0);
    lead.total=moneyLocal(total);lead.items=cart.map(x=>({name:x.name,qty:x.qty,price:x.price,meta:x.meta}));lead.status='New';lead.createdAt=new Date().toISOString();
    try{const state=Store.read(),data=structuredClone(state.data||d||{});data.leads=Array.isArray(data.leads)?data.leads:[];data.leads.unshift(lead);Store.update({data});const n=root.querySelector('#ckOrderNotice');if(n)n.textContent='Order request saved. The kitchen will confirm availability and delivery details.';form.reset()}catch{const n=root.querySelector('#ckOrderNotice');if(n)n.textContent='Could not save the order in this browser.'}
    const wa=d.contact?.whatsapp;
    if(wa){const itemText=cart.map(x=>x.qty+'× '+x.name+' — '+moneyLocal(x.price*x.qty)+(x.meta?' ('+x.meta+')':'')).join('\n');const msg=['Direct order',lead.name,lead.phone,lead.location,lead.deliveryDate,lead.deliverySlot,'Order type: '+lead.orderType,'Party guests: '+lead.partyGuests,'Total: '+lead.total,itemText,lead.message].filter(Boolean).join('\n');window.open('https://wa.me/'+safe(wa)+'?text='+encodeURIComponent(msg),'_blank')}
  });
  renderCart();
}